@config
@_book=Adnotationes in Numeros
@author=Origen
@availableStructure=chapter,verse
@compiler=Ernst Boogert
@edition=Origenis Opera Omnia, Patrologiae cursus completus (series Graeca), Charles Vincent Delarue, Origen, Imprimerie Catholique, Paris, 1857, 7, 17, The Internet Archive.
@editor=Charles Vincent Delarue
@fmt:text-orig-beta-plain={beta_plain} 
@fmt:text-orig-full={orig} 
@fmt:text-orig-lemma={lemma} 
@fmt:text-orig-main={main} 
@fmt:text-orig-norm={norm} 
@fmt:text-orig-plain={plain} 
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=Available under a Creative Commons Attribution-ShareAlike 4.0 International License
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@sectionFeatures=_book,chapter,verse
@sectionTypes=_book,chapter,verse
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@structureFeatures=_book,chapter,verse
@structureTypes=_book,chapter,verse
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:tlg2042.tlg069.1st1K-grc1
@valueType=int
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:40:40Z

