@config
@_book=Mensuris marmorum
@author=Didymus Alexandrinus
@availableStructure=chapter
@compiler=Ernst Boogert
@edition=Metrologicorum Scriptorum, Frederick Hultsch, Didymus Alexandrinus, Teubner, Leipzig, 1864, The Internet Archive.
@editor=Frederick Hultsch
@fmt:text-orig-beta-plain={beta_plain} 
@fmt:text-orig-full={orig} 
@fmt:text-orig-lemma={lemma} 
@fmt:text-orig-main={main} 
@fmt:text-orig-norm={norm} 
@fmt:text-orig-plain={plain} 
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=Available under a Creative Commons Attribution-ShareAlike 4.0 International License
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@sectionFeatures=_book,chapter
@sectionTypes=_book,chapter
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@structureFeatures=_book,chapter
@structureTypes=_book,chapter
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:tlg0357.tlg001.1st1K-grc2
@valueType=int
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:41:57Z

