@node
@_book=Adnotationes in Jesu filium Nave (fragmenta e catenis)
@author=Origen
@availableStructure=chapter,verse
@compiler=Ernst Boogert
@coverage ratio=94.15%
@description=the lemmatized form of the text tries to return as much as possible the words as a comma-separated list of possible lemmata. If no lemma could be found, the word is preceded by a "*". The lemmata have been defined by using the normalized text
@edition=Origenis Opera Omnia, Patrologiae cursus completus (series Graeca), Charles Vincent Delarue, Origen, Imprimerie Catholique, Paris, 1857, 7, 17, The Internet Archive.
@editor=Charles Vincent Delarue
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=Available under a Creative Commons Attribution-ShareAlike 4.0 International License
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:tlg2042.tlg071.1st1K-grc1
@valueType=str
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:40:16Z

*στιχ
εἶδον,ὁράω,ἰδέ,ἴδη
καί
ἀπαίρω,ἄπηρος
πᾶς
λαός
ἐκ
ὁ,ὅς
σκήνωμα
αὐτός
τουτέστι
ὅς,ὡς
ἅλως,ἧλος,ἁλίσκομαι
πλήρωσις
οὐ
γάρ
μόνος
ἐπάγνυμι,πήγνυμι
ὅς,ὡς
εἰμί,εἰς,ἐν
ὁ,ὅς,τῇ
ἐρυθρός
ἀλλά
ὅς,ὡς
θημών
πυρός,πυρόω
σωρεύω
εἰμί,εἰς,εἶμι
τύπος
ὁ,ὅς
ἀπόστολος,ἀποστολή
δηλονότι
*στιχ
ἰός,εἶμι
ἰσάζω,ἵζω,ἴσος,ἴς
*κεκραξατε
*παρεδωνε
γάρ
κῦρος,κύριος2,κύριος
σύ
ὁ,ὅς
πόλις
διατί
ὁ,ὅς
*ιεριχω
ἀναθεματίζω
προστάσσω
πρότερος,πρῶτος,πρώτη
οὗτος
αἱρέω
πόλις
μετά
ὁ,ὅς
διαβαίνω
ὁ,ὅς
ποταμός,ποταμοί
ὥσπερ
τοίνυν
προστάσσω
αὐτός
ὁ,ὅς
καρπόω,καρπέω,καρπός
προσφέρω
ὁ,ὅς
ἀπαρχή
οὕτως
κελεύω
ὁ,ὅς,τίς
ὁ,ὅς
σκύλλω,σκυλάω,σκῦλον,σκύλος
προσφέρω
ἀκροθίνιον
πρός
δέ
οὗτος
καί
γυμνάζω
αὐτός
διά
οὗτος
ὁ,ὅς
νόμος,νομός,νομή
ὥστε,ὡς
ὁ,ὅς
ἀναγκαῖος
νόμος,νομός
τηρέω
ὁ,ὅς
οἰκεῖος
δέ
αὐτός
ἐπιδείκνυμι
δύναμις
ὁ,ὅς
πρότερος,πρῶτος,πρώτη
πόλις
διχάζω,δίχα,διχάω
ὁπλή,ὁπλέω,ὅπλον
καί
μηχάνημα
αἱρέω
παρασκευάζω
καί
μονή,μόνος
καταλύω
ὁ,ὅς,τῇ
ὁ,ὅς
σάλπιγξ
ἄγω,ἠχέω,ἠχή
ἵνα
ὅταν
ἡσσάομαι
παρατάσσω
γνῶσις,γιγνώσκω
ὅς,ὡς
αὐτός
παρέχω
ὁ,ὅς
ἧσσα,ἡττάω
ὁ,ὅς
ἀφορμή
ὁ,ὅς
θέω,θειάζω,θεάω,θεῖος,θειόω
νόμος,νομός,νομή
καταφρονέω
*στιχ
*β
καί
ὁ,ὅς
προνομή
ὁ,ὅς
κτῆνος
προνομεύω
σεαυτοῦ,σαυτοῦ
ἐπεί
οὐ
δέω2,ἐσθίω,δέω1,δεῖ,ἔδω,δέω
ὅς,ὡς
εἰμί,εἰς,ἐν
ὁ,ὅς,τῇ
*ιεριχω
ὁ,ὅς,τίς
πάντῃ,πᾶς
ἀνατίθημι
*στιχ
*κς
καί
ἐκτείνω
ὁ,ὅς
ἰησοῦς
ὁ,ὅς
γαῖσος
καί
ὁ,ὅς
χείρ
αὐτοῦ,αὐτός
μένω
γάρ
ἰησοῦς
ἐκτείνω
ἔχω,χόω
ὁ,ὅς
χείρ
ἵνα
θεάομαι
ἕ,ὁ,ὅς
ὁ,ὅς
ἐνέδρα,ἐνιδρόω
προκαταλαμβάνω
ὁ,ὅς
πόλις
