@config
@_book=Panarion (Adversus haereses)
@author=Epiphanius
@availableStructure=haeresis,chapter,section
@compiler=Ernst Boogert
@edition=Epiphanius, Bände 1‑3, Karl Holl, Epiphanius, J. C. Hinrichs'Sche Buchhandlung, Leipzig, 1915-1933, Vol. I-III.
@editor=Karl Holl
@fmt:text-orig-beta-plain={beta_plain} 
@fmt:text-orig-full={orig} 
@fmt:text-orig-lemma={lemma} 
@fmt:text-orig-main={main} 
@fmt:text-orig-norm={norm} 
@fmt:text-orig-plain={plain} 
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=Available under a Creative Commons Attribution-ShareAlike 4.0 International License
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@sectionFeatures=_book,haeresis,chapter
@sectionTypes=_book,haeresis,chapter
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@structureFeatures=_book,haeresis,chapter,section
@structureTypes=_book,haeresis,chapter,section
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:tlg2021.tlg002.opp-grc1
@valueType=int
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:35:00Z

