@config
@_book=Historia Ecclesiastica
@author=Evagrius, Scholasticus
@availableStructure=book,chapter
@compiler=Ernst Boogert
@edition=The ecclesiastical history of Evagrius with the scholia, Evagrius, Scholasticus, Joseph Bidez, Leon Parmentier, London, Methuen, 1898, Internet Archive.
@editor=Joseph Bidez, Leon Parmentier
@fmt:text-orig-beta-plain={beta_plain} 
@fmt:text-orig-full={orig} 
@fmt:text-orig-lemma={lemma} 
@fmt:text-orig-main={main} 
@fmt:text-orig-norm={norm} 
@fmt:text-orig-plain={plain} 
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=Available under a Creative Commons Attribution-ShareAlike 4.0 International License
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@sectionFeatures=_book,book,chapter
@sectionTypes=_book,book,chapter
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@structureFeatures=_book,book,chapter
@structureTypes=_book,book,chapter
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:tlg2733.tlg001.1st1K-grc1
@valueType=int
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:39:07Z

