@config
@_book=Refutatio Omnium Haeresium
@author=Hippolytus
@availableStructure=book,chapter,section
@compiler=Ernst Boogert
@edition=Hippolytus Werke, Die griechischen christlichen Schriftsteller der ersten drei Jahrhunderte, Paul Wendland, Hippolytus, J. C. Hinrichs'sche Buchhandlung, Leipzig, 1916, vol. 3, 26.
@editor=Paul Wendland
@fmt:text-orig-beta-plain={beta_plain} 
@fmt:text-orig-full={orig} 
@fmt:text-orig-lemma={lemma} 
@fmt:text-orig-main={main} 
@fmt:text-orig-norm={norm} 
@fmt:text-orig-plain={plain} 
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=Available under a Creative Commons Attribution-ShareAlike 4.0 International License
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@sectionFeatures=_book,book,chapter
@sectionTypes=_book,book,chapter
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@structureFeatures=_book,book,chapter,section
@structureTypes=_book,book,chapter,section
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:tlg2115.tlg060.opp-grc1
@valueType=int
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:37:02Z

