@config
@_book=Fragmenta In Jeremiam (E Philocalia)
@author=Origenes
@availableStructure=fragment,section
@compiler=Ernst Boogert
@edition=Origenes Werke, Erich Klostermann, Origenes, J. C. Hinrichs'Sche Buchhandlung, Leipzig, 1901, vol. 3, Internet Archive.
@editor=Erich Klostermann
@fmt:text-orig-beta-plain={beta_plain} 
@fmt:text-orig-full={orig} 
@fmt:text-orig-lemma={lemma} 
@fmt:text-orig-main={main} 
@fmt:text-orig-norm={norm} 
@fmt:text-orig-plain={plain} 
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=Available under a Creative Commons Attribution-ShareAlike 4.0 International License
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@sectionFeatures=_book,fragment,section
@sectionTypes=_book,fragment,section
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@structureFeatures=_book,fragment,section
@structureTypes=_book,fragment,section
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:tlg2042.tlg084.opp-grc1
@valueType=int
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:41:07Z

