@config
@_book=Supplementum Et Varietas Lectionis Ad Catenam In Evangelium
@author=Catenae (Novum Testamentum)
@availableStructure=section,page,line
@compiler=Ernst Boogert
@edition=John Anthony Cramer, Catenæ Græcorum Patrum in Novum Testamentum, In Evangelia S. Lucae Et S. Joannis, Oxford University Press, Oxford, 1844, 2, Internet Archive.
@editor=John Anthony Cramer
@fmt:text-orig-beta-plain={beta_plain} 
@fmt:text-orig-full={orig} 
@fmt:text-orig-lemma={lemma} 
@fmt:text-orig-main={main} 
@fmt:text-orig-norm={norm} 
@fmt:text-orig-plain={plain} 
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=Available under a Creative Commons Attribution-ShareAlike 4.0 International License
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@sectionFeatures=_book,section,page
@sectionTypes=_book,section,page
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@structureFeatures=_book,section,page,line
@structureTypes=_book,section,page,line
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:tlg4102.tlg007.opp-grc1
@valueType=int
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:37:33Z

