@node
@_book=Epistula ad Africanum
@author=Origenes
@availableStructure=epistle,paragraph
@compiler=Ernst Boogert
@description=open tag without further specification. See the name of the .tf-file for it's meaning
@edition=Origenis Opera Omnia, Patrologiae cursus completus (series Graeca), Charles Delarue, Charles Vincent Delarue, Origen, J. P. Migne, Paris, 1857, Volume 1, 11.
@editor=Charles Delarue, Charles Vincent Delarue
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=Available under a Creative Commons Attribution-ShareAlike 4.0 International License
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:tlg2042.tlg045.1st1K-grc1
@valueType=str
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:41:07Z

4749	(17) Wetstenius ἔχων, Hœschelius vero et codex Regius ἕχειν, rectius. infra Hœschelius [cum Cant. ] , θεωρῶν ὅτι ἀπολείπομαι.
(22) Οὐ περὶ τῶν κατὰ Σωσάνναν μόνον, etc. Certe ipsemet lieonymus qui passim tum in præfaione in Danielem, um in proœmio explanationis n cumdem prophetam, Judæorum Porphyriique argumenta et cavllationes comta Susannæ, Belis draconisque historiam, nec non hymnum trium puerorunn, quasi de industria et ex animno colligit, cum lepsset a Ruino furectis. ib. , sibi ea quæ dixerat,
(28) Patricius Jomus, παραλαβεῖν,. Infra VVoι. steni codex, οἰκοδομῆσαι δυνάμενα. aυlυυυosttPa
ab nnione dividit, quod honus esset, Dei sententia comprobari. s Venerabilis Boda in Hexcameron pag. G, tom. IV « Notandum, inquit, quod hujus verbi adjectio hoc in loco in Hebraica veritate non habetur. Et mirum quare inter omnia quæ creasse Deus legitur, hic solummodo, id est, in secundi dici operibus probatio divinæ visionis minime addatur, quæ tamen ipsa cum cæteris quæ fecit, Deo bona ess-e demonstrantur, cum in sequentibus dicitur, « vidit«que Deus cuncta quæ fecit, et erant vide bona. » Nsi forte sicut quidam Patrum exponunt, intelligere nos in hoc Scriptura voluit, non esse bonum duplicem numerum qui ab unitate dividat et prælignrat fœdera nuptiarum. » Nec levis est ea de re apud Judæas ipsos quæstio. De veteribustestatnr hoc loco Origenes; de recentioribus nonnulla observatu digua a ﬀert AV etsthenius quæ hic apponere visum est non abs re fore. Legitur in Bereschit Rabba, Parascha 4 : Iuare non scrptum est in secundo (dio) quod bonum ? rabbi Jochanan tradidit in nomine rhbi Joni ilii Chalephta, quia in illo creata est gehenna : quia dictum est (sa. αXX, ὅ3); Nam aperta Τophta, sive gehenna a pridie, dies ex quo essum dcere pridie, et non ntalins tertius. » IPostea sic pegit : « Rabbi Chanina dixit, quia e illo creata est divisio, secundum illud : et « dividat linter aquas ct aquas. » Dicit rabbi Τebiomi : « Si divisio quæ fact ad ordinandum componendumque mundum non meretur illud, « quod honum; s quanto minus illa, quæ mundum confundit? iRathi Samuel dixit, quta illo die necdum absolutum erat opus aquarum : ideoque tertia die duplicatur illa formula, ut operum secundi et tertii dei consummatio denotetur. » Matrona quædam quæsivit ex rabbi Joni, « quamobrem dlud, « quia bonum, s
ἐκάστῳ τόπῳ τὸν ἐλλείποντα λόγον. Παρέθετο δὲ αὐτῷ ἀστερίσκον· οὐχ ὡς χρείας οὕσης τοῦ πάντως ζητηθῆναι τὸν λόγον· περιττὸς γάρ ἐστιν· ἀλλʼ ἵνα μὴ παραλείψῃ Ἰουδαίοις καὶ Σαμαρείταις ἐπιλαμβάνεσθαι τῶν ἐν ταῖς ἁγίαις Ἐκκλησίαις θείων Γραφῶν, μηδενὸς ἐπιληψίμου πράγματος ὑπάρχοντος κατὰ τῆς πίστεως ἐν τοῖς ἀπεστερημένοις λόγοις. « Successit his Οrigenes, qui uncnique loco quod deerat adjunxit, eique asterisci notam appinxit: non quod addita illa vocabula admodum necessaria sint, eum supervacua videantur; sed ne Judeis ac Samaritanis ullam calumniandi sacras foitteras, quibu-in Ecclesiis utimur, occasionem relinqueret; cum nihil in subtractis ills vocibus contra fﬁdem esset, cuod repreliendi meito posset. » tuﬁuus lh. n lnrec. adtersus llieron ymum : « Apovtatæ qu. lem et Judæiint erpretati sunt ea, quorum lectione Judæi mavme utuntur. Et quia frequenter, si disputatio incidsset, vel imutata esse aiquanta , vel deesse, vel abundare in nostris Scripturis meuticbantur, voluit Orugenes nostis ostendere, qualisapud Judæos Scripturarum lectio teneretur, et in propriis paginis vel columellis editiones earum singulas quasque descripsit; et ea quæ apud illos sunt addita vel decerpta, certis quibusque signis additis, ad versiculorum capita designavit, et in alieno, non suo opere, suas tantummodo notas fﬁxit, ut sciremus non quid nobis sed quid Judæis adversum nos certantibus, aut deesse aut abundare videtur, » idem lHieonymi conslium fuit cum ex lebræo sacras Scriptura- Latine vertit. Nam prælatione in librum Psalmorum ait : « Nec hoc dcc, quo prædecessores meos mordeam, aut quidquam de his arbitrer detrahendum, quorum translationem diligentissime emendatam, olim meæ linguæ hominibus dederim; sed quod ahud sit in Ecclesiis Christo credentium Psalmos legere, aliud Judæe singula verta calumuniautbus respondere. s Idem hb. m Apologiæ a dversus Ruliuum: « Egone, inquit, contr Septuagpnta futerpretes aliquid sum locutus, quos ante annos plurimos dligentissime emendatos, meæ hnguæ studiosis dedi, quos quotihe in conventu fratrum edssero, quorum Psalmos jusp meditatione decanto? Tam stultus eram ut quod in pueritia thoi, senexς ollivisci vellem? iuiversi tract ntus mei horum testimoniis texti sunt, cotmentarii in duodecim prophetas ct meam et eρ
(46) ἐλάσονται, ete. Hieronymus quoque præfatione in librum Josue testatur « dolere Judæos quod calumniandi eis et irridendi Christianos sit ablata occasin. » Et præfatione in librum isaiæ : « lpse mihi mercedem restituat i futuro, qui scit me ob
(56) Codex Basil , ἀπατωμένη, et ita forte legendum, licet alii codces habeant, ἀπαντωμένη. IRescribe quantocius id quod præbent codd. Cantabr. et Basil.; pessima est aliorum codicum lectυ. Noτε.
(60) Πεπρίσθαι ἐσσίαν. Eadem docet Origenes tomo undecimo in Matthæum: Καὶ Ἡσαῖας δὲ πετρίσθαι ὑπὸ τοῦ λαοῦ ἱστόρηται. Εἰ δέ τις οὐ προσίεται τὴν ἱστορίαν διὰ τὸ ἐν τῳ ἀποκρύφῳ Ἡσαῖα αὐτὴν φέρεσθαι, πιστευσάτωτοῖςἐν τῇ πρὸς Ἐβραίους οὕτω γεγραμμένοις· Ἐλθάσθησαν, ἐπρίσθησαν, ἐπειράσθησαν. Τὸ γὸρ, ἐπρίσθησαν, ἐπὶ τὸν Ἡσαῖαν ἀναφέρεται, etc. « isaiam quoque serra dissectum fuisse traditum est. Si quis vero historiam hanc non admittant, quod ea in apocrypho isaia referatur, iis credat quæ in Epistola ad Hebræos ita scripta sunt : « Lapidati sunt, secti sunt, tentati sunt. » illud enim, « secti sunt, » ad isaiam elertur, » etc. Idem de isaiæ dissectione tradunt lHieronymus in Isaiæ cap. XX et vII; Justinus martyr in Diαlοqο eum typhone Judæo, p. 273; Epiphanius De ritis prophetaarun, pas. 421; Theodoretus in hypothesi ad isaiam ab lHœscbelio edita, pσg. 74; Dorotheus in Synopi, pag. 669; tcamenius in Comment. ad llebr. m; Prudentius hymno 5 Περὶ Στεφάνωνς Sulpicius Severus epist. 2; Τertuthauus lh. De putientia, c. 14, et ib. m Carmin. adversus Maraon., epitome temp. Euseb. adjecta, p. 24; Suidas in voce Μανασσῆς; Cedrenus in Comp. hist., p. 9I, Abulpharajus llistor. dgnast. II, p. 4ὐ; Primanus in Comm. ad llebr. . Cansam martyrii ex Jdæotum traditione aﬀert Origenes homil. I in lsaam:
(65) VV ttenius et codo Basileensis, μνήματα ...εἰ ἥμεθα..... οὐκ ἂν ἥμεθα. Iufra VVetsteniυs, ὡς μαρτυρεῖτε.
(74) Idem, πράγματα, pcrperum.
(76) Μετά, deest apud Wetstenium, sed repperi
(79) Idem, πρίνου πρίσιν, καὶ σχῖνον σχίσιν· ὅτι ἐν ταῖς ἡμετέραις Γραφαῖς κεῖνταί τινες οἱονεὶ ἐτυμικροῦ δεῖν, ἔλαβέ με.
(97) VVetstenii codex, εἴ γε μήν, malo.
(1) Συγκεχωρῆσθαι τοῖς οἰκείος νμοις κρῆ
(9) Aldus, ἐξ Ἰερουσαλήμ. Idem paulo post, ἐξελέγξει λαὸν πολύν. Codex Basileensis, ἐλέγξει λαὸν πολύν.
