@node
@_book=Fragmentum in Lamentationes (In Catenis de Octateucho)
@author=Origenes
@availableStructure=fragment
@compiler=Ernst Boogert
@coverage ratio=98.2%
@description=the lemmatized form of the text tries to return as much as possible the words as a comma-separated list of possible lemmata. If no lemma could be found, the word is preceded by a "*". The lemmata have been defined by using the normalized text
@edition=Origenes Werke, Erich Klostermann, Origenes, J. C. Hinrichs'Sche Buchhandlung, Leipzig, 1901, vol. 3, Internet Archive.
@editor=Erich Klostermann
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=Available under a Creative Commons Attribution-ShareAlike 4.0 International License
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:tlg2042.tlg012.opp-grc1
@valueType=str
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:39:57Z

*ωριγενους
εἰμί,εἰς,εἶμι
ὁ,ὅς
αὐτός
ἐκ
ὁ,ὅς
εἰμί,εἰς,εἶμι
ὁ,ὅς
θρῆνος
τις,τίς
γάρ
ὁ,ὅς
*gt
δίκαιος
οὐ
δικαιόω,δίκαιος
διαλαμβάνω
δέ
ἐκεῖνος
εὐχερής
καί
ἐπί
οὗτος
μετέρχομαι
ὅστις,ὅτι,ὅτι2
εἰμί
δικαιόω,δίκαιος
ὁ,ὅς
ἄδικος
διώκω
ἐξήγησις
μέν
ὁ,ὅς,τις,τίς
δικαιόω,δίκαιος
ὁ,ὅς
δίκαιος
διώκω
ἀυτή,αὐτός,ἑαυτοῦ,ἀϋτή,ἀυτέω,οὗτος
ἐπεί
καί
ὁ,ὅς
πράσσω
καθήκω
εἰμί
καί
ὑγιής
διάθεσις
ἐνεργέω
ὅς,ὡς
εἰμί,εἰ,εἶμι
ἀτίζω,τις,τίς,τίνω
σωφρόσυνος,σωφροσύνη
ζεύς,δῖος,διά
οὐδέ
ἄλλος
τίη,ἤ2,ἤ
δέ
αὐτός
κατορθόω
*ιωσηφ
ἀναγράφω
ποιέω
ὁ,ὅς,τις,τίς
δέ
ἄδικος
ὁ,ὅς
δίκαιος
διώκω
ὁ,ὅς
σαφήνεια
εἰμί
τοιοῦτος
ἐπεί
ὁ,ὅς
καθήκω
ἐγώ
ἀτίζω,τις,τίς,τίνω
ἐπιτέλλω,ἐπιτελέω
πρόθεσις
δέ
μοχθηρός
ὅς,ὡς
εἰμί,εἰ,εἶμι
ἀτίζω,τις,τίς,τίνω
δοκέω,δοξάζω,δόξα
ὁ,ὅς
πηρός,παρά
ἄνθρωπος
θηράω
κοινωνέω
ὁ,ὅς
ὑπάρχω
πένομαι,πένης
ὅς,ὅσπερ
ἀπαγορεύω
ὁ,ὅς
σωτήρ
φημί
ἐάν
ποιός,πόα,ποῖος,ποιέω
ἐλεημοσύνη
μή
σαλπίζω
ἔμπροσθεν
σέω,σοῦ,σός,σεύω,σύ
ὥσπερ
ἕ,ὁ,ὅς
ὑποκριτής
ποιέω
εἰμί,εἰς,ἐν
ὁ,ὅς
συναγωγή
καί
εἰμί,εἰς,ἐν
ὁ,ὅς
ῥύμη
ὅπως
δοξάζω
ὑπό
ὁ,ὅς
ἄνθρωπος
ὁ,ὅς
δέ
δικαιόω,δίκαιος
ὁ,ὅς
ἄδικος
ποιέω
νοέω
ἀνά,ἄν,ἐάν
ὅταν
πρόθεσις
ὁ,ὅς,τίς
κρείσσων
ποιέω
ἀτίζω,τις,τίς,τίνω
προαιρέω
πηρός,παρά
ἄγνοια
ὁ,ὅς,τις,τίς
καλέω,καλός,κάλως,κᾶλον
πράσσω
ὁ,ὅς,τίς
χείρων
ὁποῖος
ποτός,ποτέ,ποτε,πότε,πότος
γίγνομαι
παῦλος
προδίδωμι
ὁ,ὅς
ἐκκλησία,ἐκκλησιάζω
κατά
ζῆλος
θεοσέβεια
ἄδικος
δέ
ὁ,ὅς
ἄδικος
ὅταν
καί
ὁ,ὅς
πράσσω
ἄδικος
εἰμί
καί
ὁ,ὅς
προαίρεσις
κακοποιητικός
