@config
@_book=Apology II
@author=Justin Martyr
@availableStructure=chapter,altsection
@compiler=Ernst Boogert
@edition=S. Iustini Aplogiae Duae, S. Iustini, Gerardus Rauschen, P. Hanstein, Bonnae, 2, 1911, Internet Archive.
@editor=cureditor
@fmt:text-orig-beta-plain={beta_plain} 
@fmt:text-orig-full={orig} 
@fmt:text-orig-lemma={lemma} 
@fmt:text-orig-main={main} 
@fmt:text-orig-norm={norm} 
@fmt:text-orig-plain={plain} 
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=not provided by source
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@sectionFeatures=_book,chapter,altsection
@sectionTypes=_book,chapter,altsection
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@structureFeatures=_book,chapter,altsection
@structureTypes=_book,chapter,altsection
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:tlg0645.tlg002.perseus-grc2
@valueType=int
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:39:31Z

