@node
@_book=De laudibus Constantini
@author=Eusebius
@availableStructure=chapter,section
@compiler=Ernst Boogert
@description=open tag without further specification. See the name of the .tf-file for it's meaning
@edition=Eusebius Werke, Ivar A. Heikel, Eusebius, J.C.Hinrichs'sche Buchhandlung, Leipzig, 1902, Vol. I, Internet Archive.
@editor=Ivar A. Heikel
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=Available under a Creative Commons Attribution-ShareAlike 4.0 International License
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:tlg2018.tlg022.opp-grc1
@valueType=str
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:35:43Z

20376	Der ganze Prolog bis 196, 13 fehlt in J | 2 ὦτα Hkl, ὼς τὰ Η, ὡς διὰ Ν| φωνῆς Ν|3 δεπάεσι H, δεπάεσσι, aber das σ undeutlich, N | ῥημάτων φράσει &lt;Hk1 | 4 προσποιοῦμαι N|7 δ’ &lt;H | 8 πορείαν Hkl, χορείαν HSS | ἀνθρώπων Η|13 ἐπίβολοι Η|15 θεοπρεπεῖς Η, θεοφιλεῖς Ν| 16 εἵλοντο Η, wahrsch. προεί- ὅμως HSS, μέντοι Hkl | 21 ἔτι] ὅτι vermutet Val.
3 διηγείσθω H | 6 nach χρησμοί + οἱ Hkl | μᾶλλον δὲ Hkl, μᾶλλον ἢ HSS | 7 ἐπιπνοίᾳ Hkl | 9 ἀνωτάτω H, ἀνωτάτου N | 11 ἑκατέρων H | 13 ἐφαψόμεθα, ό auf Ras. aus ώ, H | 14 Vor dem erstem Cap.: Εὐσεβίου τοῦ παμφίλου εἰς Κωνσταντῖνον τὸν βασιλέα τριακονταετηρικός HJN | χαίρωμεν HJ, χαίρομεν Ν (so Wil.) | 15 vielleicht ἐξάρχοι |17 νεμεσσήσει HN, νεμεσήσει J 19 lieber ἀνωτάτω |20 δ' HN, δὲ J | 21 . .εἴ? Hkl, εἰδ᾿ εἴ HJ, οὐδὲ N | δύναιτο HJ, δύνατιτ᾿ ἄν N | 23 περιπολοῦσιν, aber ν ausradiert u. οὐράνιοι &lt; J | 24 αὐτῶν JN, αὐτὸν Η |25 θείασοι Η, θίασοι, aber ι u. Οι auf Ras., J | 27 ἀενάων Η, ἀεννάων JN |  ἀρυττόμενοι ΗΝ u. J, aber das zweite τ ausradiert in J | 28 νοερὰ]ἱερὰ Ν.
12 τῆς ἀπειρ. δυνάμενως &lt; N | γε γεραίρουσιν Η |14 ἀναπέμπουσιν J, ἀπέμπουσιν Η, ἀναπέμπουσι Ν |19 τε Ν, δὲ HJ |  τούτων HJ, τοῦτον Ν |23 προὼν HSS, πρὸ αἰώνων Hkl | 25 καθοσιωμένος HSS | vielleicht ὕπερ ἱλάσκεται |26 δευτερείοις Val., ἴδοις HSS | 28 μεσεῦνο J | 30 ἀλήκτου Ν, ἀλήπτου Η, ἀλήστου J, vgl. 199, 5 | ἀναωλυστάνων Η, ἀναβλυστάνον, das letzte o auf Ras., J | 32 καταλάμπων Η, καταλάμπον, aber ον auf Ras., J.
6 διαρεκεὶ δὲ Η, διαρκὴς δὲ J, ὁ διαρκὴς δὲ Ν |ὁ + vor  δὲ Val. | τῆς —βασιλικῆς HJ, ταῖς — βασιλικαὶς Ν | ἀπορροίας Η |7 ἐπωνύμῳ &lt;J | 11 ὑπὸ χεῖρα J | 12 αὐτὴν Η |24 τῆ + vor φωνῇ Ν |25 τῆς ἀληθοῦς &lt; JN | nach εὐσεβείας + ἀληθεῖς J, καὶ ἀληθείας Ν |26 οὐρανίας J | 28  καταὶ Η |33 καθηγησαμένων Hkl (vgl. S. 9, 4), καθηγεμὼν Η, καθηγεμονευσάντων Ν, &lt; J.
1 λήροις Wil., ἄκροις HN, καὶ ἄκροις &lt;J | 3 οἴκους &lt;HJ | 14 ἀκροθήνιον H, J ἀκροθιν, aber vor ι ein Buchst. ausradiert | 14 πρὸ J, πρὸς HN | 15 οὐκ &lt; Wil. | 17 nach τῶν + δ’ N | nach αὐτῷ + δὲ J | 19 ἀσπαζ.] ἀποδεχόμενος J | 20 τε &lt;N | 23 τῆ + vor ῥᾳστ. N | 25 καὶ ὥσπερ — δωρ. &lt;N | 32 θείων προφητειῶν H, προφητειῶν J, προφητῶν θείων N.
8 μαρμαρυγὲς H, μαρμαρυγῆς J | μαρμ. — ἐπιλάμψεσι &lt;Wil. | 10 μὲν ἡμῖν ~ Hkl | τὸν] τοῖς H | 11 κἀ (so) + vor θάτερον H | 14 αὐτῷ Hkl, ἑαυτῶ HSS | 15 τε &lt;N | 17 ὁ + vor ἥλιος N | 21 ἀνωݲνݲ auf Ras N | 22 μόνῃ Val., Wil., μόνος HSS | ὁ + Wil. | 23 τὴν &lt;Hkl | 30 θεοῦ? Hkl | 33 στρατοπεδίας HN, -ειας, aber ει aus ι, J.
7 μεγίστων ἀγαθῶν Zimm., μέγιστον ἄγαθον HSS | 12 τὴν &lt;J | 14 ὁ δ’ αὐτὸς τὴν οὐσίαν ἀγαθὸς μόνος + am Rande H 1, &lt;JN | 15 ἰσχύει HJ | τε Hkl, δὲ HSS | 18 καὶ ἐξουσίας &lt;J | 27 ὑπειςῆλθον HJ, ὑπειςῆλθεν N | ἐννοίας H, ἔννοιαι J, ἔννοια N | 28 πεπιλημένω, ι auf Ras, H | 32 πατὴρ οὐσίας ~ J | 33 ἐκγόνοις N, ἐγγόνοις HJ.
2 σοφίας — 3 ἔρως &lt;J | 3 ἔνθεν — γνῶσις steht nach ἐπάξιος (4) in JN | 6 ὡς δὲ — 18 ἐκτυπούμενος &lt;J | 9 τοῦτ’ εἰδ. &lt;Hkl | 11 τε &lt;Wil. | 13 χορηγίας, ηγιας auf Ras., H | 15 τῆς κλήσεως στολὴν ~ N | 16 ἐπλήρου τε N, ἐπλήρουντο HJ| ὅσην N, ὅσον H | ὁ + vor ἥλιος N | 19 προβεβλημένος N, προβεβλημένους HJ | 21 κοσμηθεῖ H | 26 ἂν + Hkl | τῇ ψυχῇ HJ, τὴν ψυχὴν N, vgl. S. 204, 5. u. 19 | 34 πόματος HSS, lieber ῥιζώματος Hkl.
1 nach ἄσωτος steht in H καὶ σωστὸς, woraus Val.: καὶ ἄσωστος | ἐνδοθεὶς J | 2 ἀλλ’ vielleicht zu tilgen | οὔποτ’ ἀληθεῖ Hkl, οὔπω τἀληθεῖ HN, οὔπο (aber das letzte ο auf Ras.) τἀλ. J | 3 χρηματίσαι H | 4 ἐψευδογραφημένας H, ψευδογραφουμένας N, ψευδογράφους J, ψευδ. δαιμ. ~ J | 6 ἐψειλκθυσμένος N, ἐφελκυσμένος, α zwischen σ u. μ ausradiert Η, ἐφελκυσμένος J | 7 γυναι (2 Buchst. ausradiert) μανίας H | 8 δὲ + vor χρημάτων N | 9 δουλ. ψυχ. πνευμάτων &lt;J | 12 ὁ &lt;Wil. | 16 τῇ πράξει &lt;JN | ἐτύμως N, ἑτοίμως HJ | 17 θνητῶν J | 18 καὶ ταῖς –19 μορφ. &lt;J | ταῖς N, τὰς H | 19 αὐγαῖς N, αὐταῖς H | 20 αὐτῆς J | 21 ὁ + vor δὴ καὶ HJ | οὗτος – 23 ἐξεπιστ. &lt;J | 26 ἀξίως J | 30 καὶ + vor ποταμοῦ N.
1 μετεωρήσας H, μετεωρίσας, ι auf Ras., J | 2 ἐνστερνισμένος J | 6 καὶ δυσκ. Hkl, ἢ δυσκ. HSS | δυσκολωτέρων Val., δυσκολωτέραν HSS | 7 ἐπιβοήσεις Wil. | 13 αὐτὴν N, ἑαυτὸν Hkl | τε +Hkl | 17 δ’ + Val. | 18 Wortfolge δι’ ἐπιστήμην τοῦ θείου τῇ ψυχῇ (dann +) ἀντὶ N | περίβλημα Wil., περιβλήματος HSS | ὁ + vor σωφροσύνη HJ | 20 περιθέμενος J | 25 θανάτων H | 26 τὴν χρῆσιν Hkl, τῇ χρήσει HSS | 27 τῶν, ω auf Ras., J | 29 οἰκεῖα J | 32 πέπεισται, ει auf Ras., H.
1 αὐτὸν H, αὐτῶ JN | 5 ἀγαθαῖς, das letzte a auf Ras., J, ἀγαθοῖς HN | 9 ὰς ἐν οὐνῶ auf Ras., J | πορείας H | 13 τῶν, ω auf Ras., J 14 νέμειν H, μένειν JN | δὲ αὐτὴν HN, αὐτὴν δὲ J | 15 ἀρχῆ u. περιγραφῆ N | 17 τὸ νῦν H, τὸν ὑπ᾿ JN | 19 ὁ δὴ HJ, ὁ δὲ N | 21 ὅλως Hein. aus Valesii prorsus, ἄλλως HSS | 23 διολισθάνων H, διολισθαίνων JN | 25 τὸν] Val. vermutet θεὸν |32 εὐθυτενὴς Val., εὐθυγενής HSS.
2 αὐτὸς — ἐμφερής &lt; JN | 3 μέσοις ob richtig? 14 ἀενάους H, ἀεννάους JN | προὐβάλλετο J | 16 δεκάδι Hkl | 20 τῶν] τὴν H | 23 σημείοις HJ, σταδίοις Ν | 24 τὴν προθυμίαν HJ, τῆ προθυμία N | 25 θεσμοῖς HN, δεσμοῖς J | 26 περιβαλὼν H, περιλαβὼν JN | 30 ψίγματα H, ψήγματα, aber η aus I, J | 31 ἐποίει H | 32 ἐξάψας λαμπρὰς HN, ἐκλάμψας φαιδρὰς J | ποικίλα φέγγη Hkl ποικιλία φέγγει H, ποικιλίαν φέγγους N, ποικιλία (φέγγει &lt;) J | 33 ob οἷα?|34 ἐστεφάνωσεν N.
1 πλάτει u. μήκει H, πλάτη u. μήκη, aber η auf Ras., J, in πλάτη η aus ει N | 2 μορφοῦσθαι ob richtig?, καρποῦσθαι? Wil., &lt; J | 5 περιέβαλλεν H, περιέβαλε J, περιέλαβε N | σμαραγεῖ —αὐτῇ &lt; Val., vgl. Hom. Π. 2, 210 |σμαραγεῖ —\tκαλλωπ. &lt; J | σμαραγδεῖ ΗΝ | 6 καλλωπιζομένην  Val., καλλωπιζομένη H, καλλωπιζομένῃ N | 7 τιθηνῆν HJ, aber verändert in τιθήνην J, τιθηνὸν Ν |8 χλοάζει H | παντοίοις καὶ τοῖς φυτοῖς τε καὶ ὡραίοις ἄνθεσιν H, παντοίοις ἄνθεσι καὶ φυτοῖς (ὡραίοις &lt;) J ] 9 ἔνθυμον Η | ζωῆς &lt; J | 10 ζῶον J | nach αὐτῷ + θεῶ J | 11 ἐπίβολον H | 12 ἔκγονον, aber ἐκ auf Ras., J, ἐγγ. HN | 13 τούτω N, τοῦτο HJ | Wortfolge τοῦτο κρατεῖν H | 14 ζώων N, ζῶον HJ | 15 ἄνθρωπος &lt; Hkl | 17 ὑποχείρια H, auch J, aber aus ὑπὸ χεῖρα in J, dies in N | 18 μαθημάτων Ν, &lt; HJ | 21 ἀστέρων, aber e ausradiert, H | ἄνθρωπος &lt; Ηκλ | 26 ἔαρ Val., ἔαρος HSS | δ᾿ HSS | ἐνιαυςίων, ιων auf Ras., J | ἰσορόποις HN.
1 ἀκμῆ J, ἀκοῆ HN | 2 τ᾿ Ηkl, δ᾿ HSS | 3 ἵππον, ο aus ω auf Ras., H | 4 τ᾿] δ᾿ H | 5 ἔαρος + vor ἵστησι J | 6 πύλαις &lt; J | οὖν (δὴ Wil.) ἐν Hkl, οὖν N, ὰν εἰς H, ὰν ἐν J | 7 σοφαῖς J | 9 δὴ &lt; J | 10 ὁ δ᾿ οἷα — 18 ἐδίδαξεν &lt; J | 14 τε &lt; H | 17 nach ζωὴν über der zeile καἰ N | ἣν + Hkl | 18  nach ἐν + . B. τῷδε (vgl. z. 15 u. 20) Hkl, nicht Wil. | 19 φτὴν &lt; Hkl | 22 εἶθ᾿ ὡς — στεφανοῖ &lt; J | 23 nach ἑτέροις, wenn richtig, Lücke | 26 δεκάδων τριάδων μονάδων τε τριπλασιόνων Hk l, τρίαδων μονάδων δὲ τριπλασιόνων HSS | 28 ἐγγ. HN, ἔκγονος, aber εχυ auf Ras., J | nach μηνῶν über der Zeile δὲ N | 31 παρὰ μένειν Η, παραμένειν J | 32 αὐξουμένου J. Eusebius I. 14
1 ὑφαίρεσιν, αι auf Ras., H | 3 ἄλλων] ὅλων H | 7 ἄλλως HSS, vielleicht ὅλως Hkl | 10 ταύτη H, ταύτης JN | 11 ὁ δύο &lt; H k l | 12 περιττὴν &lt; J | 15 ἣ N, τῆ HJ | 16 ἀγενήτου N |  γεννητῶν H, γενητῶν JN | 17 καὶ τριάδος — 22 περιέχουσα &lt; J | 18 Wortfolge δύναμις εἰκότως  εἰκότως ἂν ἄρα παντὸς ἀρχὴ N | 23 περιορίζοντες HJ | μητέρα — πῆξαι corrupt! Wil.| nach μήτερα + τε Ν | πῆξαι ὅρον Wil., πηξαίορον HJ, πηξαίωρον N | τε καὶ &lt; JN | |28 παλίσσυτοι H k l, παλιςύρρυτοι HJ, παλίσυρτοι N | 31 δεκάδα] μονάδα J | 323 ἀποκαταστατικός Wil., ákatastatikqow HJ, καταστα. Ν.
5 ἀπειργάζεται J, Imperfekt falsch Wil. | 9 zwischen τοῦ u. νικητοῦ ungef. 10 Buchst. ausradiert H | 16 τῆς αἴγλης HJ | 19 ὁ &lt; H k l | 22 μία — ἐκτεινομένη ζωὴ διαρκὴς J | 24 ἔχουσα HJ | θεοῦ ? Hkl| 25 παρὸ — αὐτὸν] ὅς καὶ ἥλιος ἐστὶ J | 26 λόγων — 27 αὐγαῖς &lt; JN | λόγων &lt; Hkl 27 δ᾿ HSS, τε Hkl | 28 καταλάμπων J, καταλάμπον N | παρασκ. HJ | 29 Wortfolge τοῖς αὐτοῦ κόλποις ἀντὶ τῆς J | ἀπολαβ.] ἀποδεχφόμενος J | 30 πιστοῦσθαι] δεικνύει J | nach ὑποσχέσεις + πιστεύομεν.
3 ἀποκαθῆρε Η | 7 πολεμίων τε καὶ &lt; J | 8 καὶ &lt; Η | ἄλλων τουτωνὶ βαρβ. &lt; J | δαιμόνων Η, βαρβάρων Ν |τουτονὶ Η | βαρβάρων Η, δαιμόνων Ν |9 ἤρατο νίκας J, ἤρω (ᾔρω) το νῖκος ΗΝ | 10 δύνωνται Η | 20 δὴ u. ἁπάντων &lt; J | 21 πωτώμενοι Η | θνητῶν ΗJ | 23 πλᾶνον Η | nach πλάνον + am Rande ἀλᾶσθαι Ν | 30 μὴ ἑτέραν Hkl, μηδέτεραν HSS | τὴν] τῆς Η | 32 καὶ +  vor γένεσιν Ν | γένεσιν &lt; Hkl (nicht Wil.).
τροφή Wil., sehr wahrsch. | 12 Φερεφάτης Ν | 16 γυναιμανῶν Η | γαννυμήδους J | 23 τοσοῦτο Ν | 24 φόνοις J | αὐτοῖς Η | 25 θήγειν, η auf Ras., J | 30 μανίας J | 31 καθοσιωμίνους Η, καθως., aber ω auf Ras., J.
1 das letzte καὶ &lt; Η | 2 θαλάσσης Ν | 3 ἀκρωτηρ., ω  aus o, J | 4 nach ἁπάσης + ταῦτα Η | γλυκίονα Val. (?), γλυκειαν Η, γλύκια Ν, γλυκύτερα J |  9 τῇ φθορᾷ + Hist. Eccl. | 15 παντὸς ἀνημέρων βαρβάρων Η, πάντων ἀνημέρων βαρβάρων J, παντὸς ἀνημέρου βαρβάρου Ν | 17 αὐτοῖς ΗΝ, αὐτοὺς J | 18 καινοῦ Η | 20 δ’ + Hkl (nicht Wil.) | τί ἐχρῆν Hkl, τί χρὴ Η, τίν’ ἐχρῆν JN | 21 θεὸν &lt;  Hkl | παρελθεῖν N | 23 u. 25 οὕτω HSS, richtig, aber Syr. ever = οὔπω, u. so Hein. nach Valesii „unquam“ | 24 lieber μηθὲν | 26 παραχωρήσας HJ | 28 αὐτῶν J.
1 ἄν Wil., καὶ HSS |  3 καὶ &lt; J | 4 χάρις Η | 7 ἐπὶ γῆς Hkl | 9 δίκης ΗΝ, νίκης J | 11 ἑνὶ Hkl (vgl. S. 216, 9), ἐπὶ Η, ὑπὸ Ν, &lt; J | ωεύματι &lt; J | 13 nach παλινῳδάαν + τῆς HSS, &lt;  Hkl, τὴν Hein. | πεολημμελη auf Ras. H | βουλομένους Wil. βουλομένοις HSS | 20 οὐδένες ἦσαν Hkl, οὐδὲν ἐσῆσαν Η, οὐδὲν ἦσαν JN | 25 βαρβάρων Ν |28 νομικὸν J | 29 δαίμονος J | 31 τοῦ + vor μεγάλου J | 32 ἐπεξήει, das erste  ε auf Ras., J, ὑπεξήει ΗΝ.
1 ἐπειδὴ — 19 δεισιδαίμοσιν &lt;  J | 3 πεπλανημένα (was auf das in Vita C. befindliche πεπλασμένα deutet) H, πεποιημένα Ν | 5 ἀναπετάσας ΗΝ ἀναπετάσαι Vita C. | 6 στρατοπεδίας HSS | 9 εὐσεβείας ΗΝ | 10 μέσοι Vita C. | 13 ἐγκελ. Vita C. | 11 φωράν Val., φῶρας ΗΝ | 17 nach λυσιτελὲς  + καὶ Ν | 18 καὶ &lt; Η |19 δὲ &lt; Wil. | 20 ἔρρεξε Vita C. | 21 ἐσκύλευτο J | 22 οἵδε Vita C., οἵ γε HSS | 27 αὐτὸς HSS. οὗτος Vita C. | 29 συνεῖδεν, das erste ε auf Ras., J | 30 τοῦτο Vita C. (Cod. V).
1 nach λεωφ. + ἐκτὸς Vita C. | ἐπ’] ἐν Vita C. | 4 διεφθορόσι, ό auf Ras., J | γύννιδες J, γύνιδες καὶ ἀπροστάτῃ &lt; J | ἀποστατη, ο auf Ras., N | 8 ἐπεχείρουντὄφωρ Η, ἐπεχείρουν ἔφορος JN | 9 τῷ] τὸ Η | σεμνὸν J | nach σεμνῶν + ἀνδρῶν Vita C. | 10  οὐ HJ | οἷα τε &lt; JN | 11 καὶ + vor ταῦτα Vita C. | 12 αὐγῶν J, Vita C., αὐτῶν Η, αὐτοῦ Ν | 13 ἐλύετο J, λύετο ΗΝ | βασιλικῶ, ω auf Ras., J | 16 nach τὰ + μετὰ Η | 18 ἀρρωγὸς J | 27 καὶ οὐκέτ’ — 218, 33 ἐπαιρόμενοι &lt; JN.
5 βωμοῖς &lt; with images and altars Syr. = καὶ (?) ἀγάλμασιν καὶ βωμοῖς, vielleicht so | κατὰ + vor τὰ πάτρια Val., aber these (Deities) of their fathers Syr. | 24 ἀνεπηγερμένα Η | 26 ἰδέαν Η.
1\tοἱ Val., οἷς HJ, οἷς οἱ Ν | δ’ HJ, τ’ Ν | 2 nach ἀράμενοι + κακοὶ κακῶς ἀπολώλασι Ν | ποῖ — 4 ἠξίεσαν &lt; J | nach ποῖ + δὴ Ν | 6 lieber θαρσοῦντες J | 7 καμνόντων Η, ξοάνων J, καμόντων Val., wie Vita C. Cod. V | 8 περιπεφραγμένος Vita C. | 14 ἀνεξαλείπτοις ἐγχαράξας τύποις Vita C. | 16 nach φυλακτήριον + κηρύττων εἰδέναι Ν | 17 καὶ + vor Ν | οὕς Hkl, οἷς HSS | 19 εἰδέναι θεόν Vita C.; θεὸν εἰδέναι JN, εἰδέναι βασιλέα Η | 23 μὲν] μὴ Η | οὐράνιον JN | 28 τὴν N, J, aber v auf Ras., J, τῆς Η |καὶ &lt;  vor ζωῆς Η | 29 αὐτοῦ Η, αὐτοῦ J, ἑαυτοῦ N | καταστὰς ἀγαθῶν Ν | 30 σωτῆρα γεραίρων αὐτοῦ Ν.
7 πλήθει J Ι 9 γλῶσσαι N Ι 11 δεισιδ., ει u. ι auf Ras., J Ι 12 οἷά Hkl, vgl. doch S. 9, 11 Ι 19 δυνατὸν ἦν αὐτοῖς H, δυνάμει J, ἠδύναντο N Ι 23 φρενοβλαβίας H, φρενοβλαβείας, aber ει aus ι, J Ι 24 βραχὺς &lt; N Ι 25 ριπῆ H, ῥοπῆ JN 30 τοιοῦτον NJ, τοιοῦτο H Ι 32 nach μόνου + βασιλέως J.
1 αὐτοῦ Hkl Ι 2 μεγίστῃ u. 3 περικαλλεστάτῃ Val., μεγίστην u. περικαλλ την HSS Ι 3 καὶ &lt; vor τῶν Ν Ι δὲ λοιπῶν ∾ J | 6 ἀνομβρίσαντος HJ Ι 12 N Ι τούτω J Ι 17 πλουσίαις JN, πλουσίως H Ι 20 χώρα H Ι μυσ 21 τῆς + Vita C. | πρώτης N, πρὸ τῆς HJ Ι 22 τὰ &lt; J Ι 27 γένος H, θρόνον JN ἐτῶν + am Rande H Ι 28 καὶ αἰτοῦ γένει &lt; J | αὐτοῦ Val.. αὐτῶ HN Ι τῆς &lt; JN 31 τὰ &lt; N Ι 33 ἄριζοι
3 δὲ &lt; H Ι 6 πέρι μακρὸς] περίμακρος N Ι 7 τουτὶ] τὸ J Ι 8 πολὺ δὲ νοῆσαι H; ob θαυμασιώτερον? Ι 12 προσπτύει Wil. Ι 14 κατεγγελᾶ, wie es scheint, in H | ἄνθρωποι JN, ἀνθρώποις H Ι 15 συστησάμενοι Ν, συστησαμένοις HJ Ι ὡ Η, ὡς JN, &lt; Wil. Ι ἐκπαιδεύεται J Ι δὴ Wil., ἄν HSS Ι 16 πτοεῖσθαι, ει auf J Ι 21 οὐκέτ' Wil., οὐκ HSS Ι 24 τε] δὲ J Ι 25 δὲ Hkl, δὴ HN (so Wil.), &lt; J Ι κἐκραγεν H, κέκραγε N, διακέκραγε J Ι 28 ἔθ' ὡς J, ἔθος HN, aber in N steht etwas über der Zeite Ι 29 βασιλικῆς Wil., βασιλικοῖς HSS Ι 30 εὐσεβεία N Ι 33 ἵλεω H Ι τῆν γῆν J.
1 παντοῖοι H, παντοίαις JN Ι 2 θνητὸν Hkl, θνητῶν HSS Ι 4 ὀφειλ H, θεοφιλεῖς JN Ι 5 τὰ] τὰς J Ι 9 τὸν] ὧν H Ι θεοφιλῆ N Ι 11 διορθ., ο auf Ras., J Ι 13 ὑψίζυγος, ι auf Ras., J Ι ὑπὲρ πηδαλίων ὀχούμενος Val., ὑπερπηδᾶ αἰωνοχούμενος HN, ὑπερπηδαλιουχούμενος J Ι εὐθέα N Ι τε + vor περαίνων N Ι 20 οἷός τε &lt; Hkl Ι 21 δὴ 3, δὲ HN Ι καὶ σαρκὸς J, καίσαρος, H, καὶ σαρός N Ι 22 nach καταλαμβάνεσθαι steht in J: τῶ δὲ θεῶ δόξα εἰς τοὺς αἰῶνας τῶν αἰώνων. ἀμὴν. Die letzten Worte von μακραῖς (Ζ. 17) bis ἀμὴν so geschrieben, dass sie ein Kreuz bilden. — Das Übrige fehlt in J. — H hat hier . . . . . . + τριακονταετηρικός +, dann ein grosser leerer Raum, und dann folgt mit sehr grossen Uncialbuschstaben ευσεβίου τοῦ παμφίλου. βασιλικός. — In N ist hier Absatz.
2 τὸ H Ι βασιλέως N Ι nach θεοῦ + τῶν ὅλων N Ι 4 σῆς + Val. Ι 5 δὴ N, δὲ H Ι 11 μαρτύριον + Val Ι οὐ Val., ὁ H, ἁ N Ι 12 ἀλλ’ &lt; N Ι 14 ἀθεὶ H Ι ἄν &lt; H Ι 21 ἀλλ' ἢ H, ἢ γὰρ N Ι 22 εἰ &lt; H Ι 24 οἰήματί Κε οἰήμασι τι δοκησισόφων καὶ N | 26 οὐ μόνον ἀλλὰ, vgl. 225, 24 Ι 28 διδασκαλεῖα Val., διδασκαλίας HSS Ι 29 τε &lt; Hkl Ι θ’ N, τ'
2 πρός με λέγων ∾ N Ι 7 nach μετάνοιαν ungef. 4 Buchst, ausradiert N Ι 8 τὰς αἰτίας — σπουδῆς &lt; Hkl Ι 9 κρείττονα — ἐπίπνοιαν Wil., κρείττονι — HSS Ι 12 ἀθεὶ H Ι 13 ἀγαθῶ H Ι 16 εἰς + Val. Ι τοῖς πᾶσιν N Ι 19 μαθάνειι das zweite α auf Ras., H Ι ἡμῶν θεοῦ &lt; N | 23 ταῦτα, τα über der Zeile, 11 nach μόνον + δὲ N Ι nach τε + καὶ H Ι 25 δεομένοις — 20 τούτων &lt; Ν | 31 &lt; H, + über der Zeile N Ι οὐδαμὴ N, οὐδ' ἅμα Η Ι 32 ἂν &lt; Eusebius I.
2 τῶν ἐν τὸν ἐν H Ι παριόντες H, Syr. leave, wie bei παριόντες 12 in N Παρορῶντες Ι 3 τε + vor καὶ πολ. N Ι 4 χρυσόφορα H, χρυσόροφα N (falsch, wie Syr. their roofs variegated with gold) Ι 6 τῷ &lt; H Ι 8 τοῦ Hkl, τὰ Syr. that these many things should thus be Ι 9 διαφέροι H | 16 τῶν σοφῶν richtig, nach Syr. the great maker and lawgiver of these instances of wisdom (τούτων σοφὸν Lowth, ötig!) Ι 17 ὑπερεκπλάττεσθαι Η | 18 nach + τοὺς N Ι 20 μηδὲ μὴν Hkl, μνήμην ΗSS | τοῦ ποιητοῦ καὶ δημιουργοῦ N Ι but not that we should honour or worship thern by means of any similitude of Him, who is their Maker and Creator (,,sed non ut veneraremur nisi in eius similitudine, qui est eorum creator") Syr. (falsch!) Ι 21 nach σέβειν + πρὸ παντὸς τιθεμένους τῶν ἄλλων N Ι 22 τὸν &lt; N Ι 24 ἐπὶ + Hkl Ι Wortfolge τοῦ τρίβωνος τὴν ἔξωθεν N.
1 τοῦ φιλ. &lt; Wil. Ι 6 nach μονογ. + λόγον nach Syr. the only Word Ι 8 αὐτοῦ H, ἑαυτοῦ N Ι 12 ἅρρ*τος H Ι 13 οἱ θεῖοι Hkl, οἱ ἱέρειοι HSS Ι 14 τε H, δὲ N Ι 16 προεμβάλλει H, first appoint Syr., παρεμβάλλει N, Dem. Ev. Ι 19 δὲ Val., Dem. Ev., γε HSS | ὁμωσγέπως Η Ι 21 οὐθ'] οὔτ' Η Ι 24 Syr., ἥ HN Ι 25 καταφαίνεται N, καὶ φαίνεται Η Ι 26 τὰ &lt; H Ι 28 ἢ + τιθηνὸν N.
4 καὶ &lt; Hkl Ι 6 Λαὶ + vor τῆς Val. ötig; &lt; HSS u. Syr.) Ι αἰῶνα ζωῆς ἀθαγάτου βίον (βίον &lt; Hkl) HSS, to the length of the life is immortal (,,peregit vitam diuturnam vitae quae non est mortalis") Syr., μακραίωνα ζ. ἀ. βίον Val. (Wil.) Ι 9 μὲν + Ηkl Ι 11 ἀναισθήτου Val., senseless Syr., ἀλογίστου HSS Ι 14 φθορὰς Val., changes Syr., ὥρας HSS, φορὰς Hkl Ι 19 nach κάτω + τε H Ι πλάτη — μήκη Val., πλάτει — μήκει HSS Ι 21 τοῦτο H, τούτω N Ι 23 διατόνοις HSS, τόνοις vermutet Val. (Syr. unklar: has made well to combine and to harmonize aecording to their several nieasures, „adiunxit et adaptavit his variis extensionibus") Ι 28 βυθῶν ἄχρι θαλάττης auf Ras. N.
1 αὐτὸς H, αὐτὰ Ν | τὰ γαστρὸς κυούμενα, Η, τὰ κατὰ γαστρὸ̣ς κουφορουμενο N; Syr. those (beings) which are inwardly coneeived in the womb 8 σχήμασι HSS, so auch Syr.: into the forms peculiar to each species; χρώιασι laai Hkl Ι 16 σώματι Hkl, with bodies (= σώμασι) Syr., σώματα HSS Ι nach ὕλῃ &lt; τε N, Syr. Ι 17 nach φθαρτῇ ein zweites ὕλη in H Ι Wortfolge ἀλόγων ζώων N 1 18 εἰλεῖσθαι Hkl, εἰλίσθαι H, εἱλῆσθαι N Ι ἀλλ’ οἱ N, ἄλλοι H; but these things they (do) Syr. | 19 ἀνωτάτω Hkl | 24 nach ἐν + dv (so) H.
2 τῆ οὐσία N Ι 3 θεοῦ λόγος nach Syr., θεὸς λόγος HSS Ι ἀεννάου N Ι 4 λόγοις ἀρρήτοις Val., in words unutterable Syr., λόγος ἄρρητος HSS Ι 8 δ' &lt; Hkl 9 πρακτέ*α H, πρακταῖα Theoph. gr. Ι 10 ἀδύτου μυχοῦ Hkl nach ἀδυτῶν μυχῶν Theoph. Ν, in the privaey of retirement Syr., αὐτοῦ μυχοῦ HSS Ι γεγεννημένος N, Theoph. gr., γεγενημένος Η | 11 ἀκατωνομάστω H Ι ὃς N, Theoph. gr., ὅ H Ι 14 τῆς ἐκ Theoph. gr. (u. Syr.), ἐκ τῆς HSS Ι 15 μεταλαμβάνουσιν Theoph. gr., reeeive Syr., μεταλήψεσιν H, μετέλαβον N Ι 16 πώποτε &lt; Ν | 17 δὲ Theoph. δ' ὁ H, δὲ καὶ N Ι τε &lt; N, Theoph. gr., vielleicht richtig | 19 δυνάμει H, Theoph. gr., ∾ N N Ι 22 das zweite θεοῦ über der Zeile in H Ι 25 ζωῆς nach Syr. upon all life andreason . ., ζῶα Val., ζῶν HSS Ι καὶ &lt; vor H Ι 27 τε &lt; N Ι 28 nach διεστῶτα + τὰ H Ι τε + vor γῆν N Ι τὴν γῆν H Ι κατὰ vor θαλ. N.
7 διαφορὰς H, various observances Syr., διατριβὰς N Ι 9 θνητῆς Val.. a mortal — life Syr., θνητοῖς HSS Ι 10 τοῖς δ’ H, τῆς τ' N Ι μετουσίας H, μετουσίαν, aber ν aus ς, N Ι 13 καὶ μετ' αὐτὸν &lt; Hkl Ι ἀκολούθως will Val. nach versetzen, aber Syr. ist dagegen Ι 14 μεσσεύων H Ι 15 γεννητὴν, das Kweite v über der Zeile, N Ι 16 οὗτος HSS, οὕτως Wil., ἀρραγὴς οὖτος ὁ HW Ι 22 ὄ ; auf Ras. H2 Ι 23 φυτουργὸς N, &lt; H, Saviour Syr. Ι 26 εὐθέα Η | τὸ Ν, τότε 27 καλλιτέχναν H | 28 ἀγαθὸς + Val., as a good Father beget a (,,as" Lee good Fruit Syr. Ι 31 αὐτὸν H.
9 vgl. Theoph. Syr. I, 26. — 24 vgl. Theoph. Syr. I, 27. — 26 vgl. Joh. I, 1. - 31 vgl. Eph. 4, 6. — 32 vgl. Theoph. Syr. I, 28. 2 σεπτέον (Hkl) nach Syr. worship, σκεπτέον HSS Ι 4 deHkl, δὴ HSS Ι 9 νήπιον H Ι 13 εἶναι &lt; N Ι 14 καὶ + vor πόδας H Ι 22 εἰ δὲ σύνθετος N, ἀσύνθετος H Ι 22 αὖ Val., again Syr., ὂν HSS Ι 29 οἷα &lt; Syr. Ι δ’ &lt; H Ι H, ὡς aus ὁ N Ι ὁ + vor αἰσθ. über der Zeile N.
? Hkl, vgl. 334 13 ἀφανῶς Val., invisibly Syr., ἀπλανῶς HSS Ι 15 nach περιλαμβάνει + τε Η Ι 16 εἷς ἥλιος ∾ N Ι ἀλλ’ οὐ H, Dem. Ev., ἄλλονς N Ι καὶ + vor απ. Ν Ι 20 άλλα HSS, ἄττα Dem. Ev. Ι 21 ἐπιχειροῦντα Wil., ἐπιχειροῦντος HSS Ι 27 οιτο H, Dem. Ev., ἐπιβάλοιτο N Ι 28 μυρίων H, Dem. Ev., μυρίας N Ι 29 κ τορικῆς &lt; Dem. Ev. (nicht
6 ἀλλ’ οὐκ HSS, ἆρα Dem. Ev. u. wahrsch. Syr. Ι ἐπεὶ Dem. Ev., ἐπὶ H, ἐπειδὴ N Ι πολλὰ &lt; N Ι 8 μόνον H k 1, μὲν ὃν H, μὲν ὅντα N Ι 9 nach τεχνίτην + N Ι ἐπαινεῖν ἀναγκ am Rande und dann αιον τὸν N Ι τὸν &lt; H Ι 10 σύμπαντος Ras. H Ι 11 ὑφεστὼς H Ι 12 ὁμολογεῖν Dem. Ev., bless Syr. Ι 16 vielleicht ζωογονοῦσαν Hkl, vgl. 232,3 Ι 18 nach φωτὸς + καὶ Ν | προσβολὴ N, Dem. Ev., incidence Syr., προβολὴ H Ι 19 φωτὶ H Ι 20 δὲ Dem. Ev., τε HSS Ι καὶ αὔξει N, αὔξει τε H, nur αὔξει Dem. Ev. Ι 21 τὴν ἐν τῷ παντὶ Dem. Ev., with respect to all things Syr. Ι 22 nach πυρὸς + μὲν N Ι 24 δὲ H, Dem. Ev., τε N Ι 25 τοῦ auf Ras. H Ι 27 τε &lt; Hkl Ι 28 nach οὐρ. &lt; τε N Ι 29 ἔτι H, εἴ τι N Ι 30
8 ἔν τε &lt; N Ι ψυχαῖς HSS, or in the beeings (οὐσίαις) irrational Syr., ψυχαῖς καὶ σώμασι λογικοῖς τε καὶ ἀλόγοις Dom. Er. Ι 10 H Ι 14 τοσοῦτος auf Ras. H Ι 18 καὶ &lt; Η | 19 Wortfolge γένος ἀφρόνων Η | ἀλλὰ καὶ Ν, οἵδε καὶ Η | 23 γε &lt; N Ι 24 εἰδωλοπ. N | 28 μαθητῶν H | H Ι 30 χρῆν H Ι 31 οἵδε &lt; Hkl Ι τε N, δὲ
1 ἔτι τὴν — ἀκράτειαν Val., and again the appetency to the intemperate lusts Syr., ἐπὶ τῆ — ἀκρατία HSS Ι 2 ἡδονῇ H Ι 4 καὶ (Hkl), also Syr., γὰρ HSS Ι 6 ἐπεφήμισαν, nach ι ein Buchst, ausradiert, H Ι 7 εἰλεῖσθαι Hkl, εἰλίσθαι H, εἱλίσσεσθαι N, moved Syr. Ι 8 Wortfolge ἀλόγων ν auf Ras.) ζώων N Ι 10 τούτου H Ι Π· ἀνδρῶν &lt; Wil. | 14 ἀλλὰ &lt; H Ι 16 Κνίσσας Ι 18 ob ἀλλὰς? Hkl Ι 19 ἐπανάγνοις H, ἐπανάγκοις N, forcible Syr. Ι 19 nach δυνάμεις + τε N Ι 21 γε Val., τε HSS Ι 25 οὐδὲ μὴν Hkl, οἱ δὲ μὲν H, οἱ δὲ μὲν &lt;) N, nor Syr. Ι 27 αὐχοῦντες Val.(?), who are boasted Syr., H, αὔξοντες N Ι οὐκ&lt; Hkl Ι Wortfolge παρ’ ἑαυτοῖς (aus 28) vor οὐκ ἔγνωσαν N 28 παρ’ ἑαυτοῖς &lt; hier N Ι τε über der Zeile N Ι 31 Μελίκαρθον nach
2 ἀρράβων N | Δουσάρην inschriftlich Wil. | καὶ &lt; vor Ὄβ. N Ι ὄβοδον H, ἄβδον N, Syr., Ὄβοδαν Val. Ι οὶ Γέται τὸν Wil. (auch Syr.), οἰηγεητὸν H, οἰηγεκτὸν N Ι 3 Ζάλμοξιν nach Syr, Ι Μόψιον N Ι Αμφιάρεων, εων auf Ras., H Ι 4 ἄλλοι &lt; (Hkl) nach Syr. Ι τῶν θνητῶν Wil., τὴν θνητὴν HSS Ι 5 δὲ N, but Syr., δ’) H Ι 7 θνητῶν HSS Ι ὅσην H Ι 8 βλαστόντας, nach ο ist ῦ ausradiert H Ι 8 καὶ τὰ— 27 καὶ θανάτους &lt; Ν Ι 11 διδασκαλεῖα Hkl (vgl. 32, 19), διδασκαλία H, doctrine Syr. Ι 12 σαντας Hkl Ι 17 καὶ + nach Syr. Ι 18 μὲν &lt; Wil. Ι 21 φρενοβλαβίας Η Ι 22 (?) falsch Wil. I 28 nach οὐδὲν + δ’ H Ι 31 παῖδας Val., πέλας Η, πάλας N.
1 δὲ N, δὴ H Ι 6 φρενοβλαβία H Ι 15 ταῦτα N, τὰς H Ι 17 τῷ δ’ αὐτῷ τούτῳ Val., τὸ δ’ αὐτὸ τοῦτο HSS Ι 18 μηνὶ, ὶ auf Ras., H, μηνὸς N Ι μεταγειτνιῶνι H, μεταγειτνιῶνος N, μηνὶ μεταγειτνιῶνι Porph. u. Praep. Ev. Ι ἱσταμένους N Ι 20 τρεῖς N Ι 22 ὡλοκαύτιζεν, ι auf Ras., H Ι 24 Ἀμώσης H, Ἀμόσης N, Ἄμωσις Porph., Praep. Εν. Ι 25 ἐπιτίθεσθαι] ὑποτίθεσθαι vennutet Viger Ι 26 τῶν Διον. H Ι διασπόντες H | 29 λαοδικία H Ι 31 δουματηνοὶ δὲ Val., δουματην οἱ δὲ HN, δουμάτης οἱ δὲ Praep. Ev., δουμάτιοι Porph., δουματάνη nach Syr.
1 Ἀρραβίας N | 2 Λεὼ κόρας Wil., Λεωκόρας HN, Πραξιθέας Porph., P Ev. Ι 5 καὶ νῦν HN, γε νῦν Porph., Praep. Ev. Ι 6 τῆ Η, τὴν über der Zeil Λατιαρ. Wil. Ι ἑορτῆς Η | 10 τριακοσίους HN, Syr., διακοσίους Val. | 11 (?) ὀνομαστὶ Hkl, αὐτὸ ὅνομα H, ὠνομαστὶ ω auf Ras.) αὐτὸν ν auf Ras.) N Ι 13 Ἀβοργηνῶν N Ι φησὶ τοὺς αἰτηθ. ( οὖν &lt; ) H Ι 15 τῶν + vor κακῶν N | 18 τρύχωτο H Ι 20 ἄλλοις H Ι 33 τῶ N, τὸ H Ι 25 τε + vor γωνίᾳ Ν | μόμοις τε H, καὶ νόμοις N Ι 27 ἀγριουμένων N Ι 30 κατὰ &lt; vor κώμας
6 προσδίεφθ., προσ über der Zeile, H Ι 7 καὶ τὰ Hkl, τ' H, τε καί τ' Ν Ι 24 ἀποπνίγοντες, ι auf Ras., H | τούτους H | 31 ἀνδρῶν H, ἀνθρώπων N Ι 33 προοίμι ἄττα Hkl, vgl. 236, 3, προοίμια αὐτὰ HSS.
1 οὖν N, ἂν H Ι 3 πλανώμενον N, πλαττόμενον H Ι 4 ἀτιθάσσων N Ι S N, τοῖς H Ι nach πάντων ähr 8 Buchst, ausradiert H Ι 18 καὶ πῶς H δ’ N Ι 20 τε H, που (aber ως über der Zeile) auf Ras. N Ι 21 ἤ N, ἥ 11 Ι 27 φύσιν + am Rande H, mortal in their nature Syr., &lt; N Ι ἀν ταύτη πη H, vgl. 244, 4, ἀναγορεύουσι (ουσι auf Ras.) κατὰ τὰ auf Ras.) (τ u. das letzte a auf Ras.) N Ι 29 αὐτῶ H, ἑαυτῶ Eusebius I.
3 εἴη N, εἰ ἐν H Ι 5 ἄγαλμα &lt; Wil. Ι 9 αὑτοῦ H, ἑαυτοῦ N Ι H | μετεβάλετο N Ι 10 ἄν + Hkl Ι 12 τι + Wil. Ι 16 προυβέβλητο N, Dem. Ev. Ι ἀνθρωπίνου Dem. Ev., human Syr., ἀνθρώπου HSS Ι 20 τοῦτ' H Ι 21 τιθασεύειν HSS Ι za δένδρα &lt; (Hkl) nach Syr. Ι 26 ἐπωδὰ H Ι ἀλλ’ οὐκ ἀλόγοις H, Syr., N Ι 32 ἐπιμελόμενος, ό aus ω, H Ι ὀφθαλμοῖς &lt; H, ὀφθαλμοῖς ἦν am Rande N, to mens bodily eyes Syr., + z.B. παρεῖχεν Hkl, vgl. 246, 21.
1 τερατείας Hein., signs Syr., τεραστείας N, τεραστίας H Ι 3 μόνον Hkl, vgl. doch 90, 1 Ι 4 συναισθέσθαι H | 5 πάλιν αὐτὸς H, Dem. Ev., ∾ Ν Ι 10 ὃ H, Ev., δν Ν | 12 καὶ + vor ἐν τῷ H, Dem. Ev., &lt; N Ι τε N, Dem. Ev., &lt; Η | 13 τῶν + vor ἐπὶ γῆς N, &lt; H, Dem. Ev. Ι 14 ἀποκεκλεισμένος Dem. Ev. Ι 17 παγόμενος Dem. Ev., reeeived Syr. Ι 19 διαιρουμένου Η | 24 τοι Dem. ν., τι ΗSS 29 κωλύη H Ι 33 u. 244, 1 δ’ ἄν H, Dem. Ev., ἂν N Ι 33 ἐφάψεται Η, Hkl, ἐφάψαιτο N, ἐφάψοιτο Dem. Εν.
1 ἐφάψηται Ηkl, ἐφάψαιτο HSS, ἐφάψοιτο Dm. Εν. Ι καὶ + vor αὐτίκα N Ι 2 τε Dem. Ev., γε HSS Ι 5 δεικνύς N Ι 9 καὶ &lt; vor παραδ. H Ι 10 τόπον, das ο auf Ras., H Ι 12 ἀλλ’ H, &lt; N, Th. gr. Ι ἢ Th. gr., &lt; HN Ι 13 ἴσχεν αἰτίαν besser! Ι πολυθρύλλητον N, Th. gr. Ι 14 καὶ + Th. gr. Ι 15 ἀναβιώσεως Th. gr., resurrection Syr., ἀναμνήσεως HSS Ι 16 δέ ἐναργῶν N, διενεργῶν H Ι 17 οὑν &lt; H | 18 τούτῳ τε αὐτῷ Hkl, τε τούτω αὐτῶ H, τούτω αὐτῶ N Ι 21 ἀπέπτη H, Th. gr., Syr., ἀπέστη N Ι 24 συμψήσας Hkl, συνεψήσας Th. gr., led on (,,tangere fecit“) Syr., συμψηφίσας HSS Ι αὔτ' ἂν Val., ὅτ’ ἂν H, ὅταν N, οὐκ ἄν Th. gr. Ι αὐτῶ H, Th. gr., ἑαυτῶ N | (26 φθορᾶ — 28 ὴξιοῦτο &lt; Th. gr.) Ι 26 αὐτός αὐτὰν HSS Ι 28 τέλος H Ι οὔτ' Th. gr., οὐκ HSS Ι ὅπη ποτὲ ὑπῆρχε Th. gr., where He remained Syr., ὅποι ποτ’ ὑπῆρχεν H, ὅποι ποθ’ ὑπῆρχε N.
9 διήληκεν (d. h. διήθλησεν) Th. gr. (besser!), overcome („superavit“) 10 ἐπειδὴ Th. gr., ἐπεὶ δ’ H, ἐπεί γ' N Ι 13 ᾠκονονομεῖτο Th. gr. Ι δυεῖν H, δυοῖν Th. gr., N Ι 14 τοῦ παντὸς δράματος &lt; Th. gr., make His whole and egress from this world matter of shame („et totum sum ut ex mundo pudoris fecit Syr. Ι 15 τοῦ βίου &lt; Wit Ι 17 ἦν &lt; Th. gr. Ι 19 τοῦ θεοῦ Th. gr., the Word of God Syr. | 20 H, Th. gr., ἐπαγγειλάμενον N Ι 25 διαδήλως Th. gr. (besser!) | 26 σκότιον Th. gr. σκοτεινὸν HSS Ι κρύφιον Th. gr. (besser!) Ι 80 ἐπ’ HSS, ὑπ' Hkl.
1 ἦν Th. gr., ἦ HSS Ι 3 παρίστη Th. gr., παρίστα HSS Ι τὸν HSS, besser: ὕσιατον Th. gr., last Syr. Ι 4 ζωῆς τε &lt; Th. gr., Syr. Ι καὶ σωτηρίας steht nach ἀθαν. in N Ι 5 nach πυρὸς + τῆ φύσει Th. gr. Ι δεῖξαι τι σκεῦος Th. gr. (besser!) Ι 6 ἂν ἄλλως ∾ Th. gr. (besser!) Ι τῶ &lt;) πυρὶ Th. gr. Ι 7 αὐτὸ σῶον ∾ (besser!) Ι τοῦ πυρὸς ἐξελὼν Th. gr., H, ∾ N Ι 9 ἐκέχρητο Th. gr. Ι 11 χρησίμην Th. gr., χρησίμως HSS Ι μὲν &lt; Th. gr. Ι 12 τῶ θνητῶ N Ι ( παραδ. — 13 θανάτου Th. gr.) ·Ι παραδοὺς N Ι 13 μακρὸν Hkl, μακρὰν HSS Ι 19 ἀναρτᾶν, das erste v aus μ, H Ι 20 κρείττονας — 21 παρεῖχεν anders in Th. gr. Ι 21 ἐχρῆν Th. gr., χρῆ HSS Ι 22 διενεργοῦς H Ι 25 πᾶσι τοῖς ἔθνεσι Th. gr., H, ∾ N Ι προβληθεῖσαν Th. gr., H, προκαταβληθεῖσαν N Ι 26 λαβεῖν Th. gr., reeeive Syr.
1 τῶν ἐθωῶν &lt; Th. gr., Syr. | 2 ἀναδέξαιντο? vgl. 31, 8 | 7 αυντάττων HSS, συνέταττεν Hkl | 10 lieber μηθὲν | 12 διενεργοῦς H | 15 εἴη αἰτία ~ N | ἡ + vor τῆς N | 17 ὐπονενικημένους θανάτου &lt; H) | τοῦ + Th. gr. | θνητοὺς| ὀνητοὺς H | 18 (τοῦ 〈) θανάτου N | 27 θεῶ ὅλων Η, ~ N, τῶν ὅλων 〈 Hkl | 31 ἀσεβείᾳ Val., ἀσεβείαις HSS | ἐνισχημένων N | ἀντιψύχου Hkl.
6 Joh. 1, 29. — 7 Jes. 53, 7.-9 Jes. 53, 4—6. — 28ff. vgl. Euseb. Praep. Ev. V, 1 = 178 d ff. 1 ἐλέλυτο Ν, ἐλύετο  Η | 2 ἀπατηλὴ Ν | 3 θῦμα Τh. gr., Syr., θῦμα, aber ein Buchst, ausradiert nach θ, H, θαῦμα N | 6 Wortfolge λέγουσαι ὧδέ πη N | 16 οὖν am Rande H | 18 ἑταῖρος H | 20 τὴν ἀπαρχὴν Th. gr., H, ὡς ἀπαρχὴν N | 22 πάλαι συντ. H, παλαιῶν N, πάλαι Th. gr. | 23 τοῦτο Th. gr., τοῦτ H, τοῦθ´᾿ H | 25 δὴ H, δι᾿ N | 26 δὴ Val., δι᾿ HSS | 29 ἐπαρχίας καὶ &lt; H.
4 καὶ N, ἢ H Ι 5 κατὰ δαιμόνων hierher versetzt von Val., nach ἀποτρό- παιον in HSS Ι 6 Wortfolge παλαιῶν τε Val., τε παλ. HSS Ι λύετο H Ι 8 ἄγη H Ι 9 πολιορκίαι, ορ auf Ras., N Ι εἷς + Val., one Syr. Ι 11 ἄσπειστος Val., peaceless Syr., ἄπιστος HSS Ι 12 ἐθνῶν Wil., ἐχθρῶν HSS Ι 13 H Ι σωτηρίας τε Val., ötig, vgl. 250,5 Ι 14 βασιλέως. king Syr. HSS Ι 20 ἀποτεμοῦντες H Ι 21 Ἀρράβων N Ι 22 καὶ + Hkl Ι 21 ἀληθῶς ἀλήκτῶς Wil. Ι 31 καθῆςε H.
3 πάντων H Ι 4 ἄχρι &lt; Hkl Ι 7 τὸ &lt; Hkl Ι μέγα auf Ras. N Ι 8 ἐθέλουσι das erste ε auf Ras. H Ι 9 δαιμόνων H, ἐλέγχων N Ι 10 τούτου, ου auf Ras., N, τούτω H Ι 15 πατρὸς Val., Father Syr., πρὸς HSS Ι 18 οἰκετείας τε H, household Syr., οἰκίας N Ι 19 ὅπη H, ὅποι N Ι θέλοι H, θέλει N | 25 ποτάμων N, τῶν ποτάμων H, ποτάμου Vet. Test. Ι περάτων N, Vet. Test., τῶν περάτων H Ι 28 λήψηται N, οὐ μὴ) λήψεται Vet. Test. Ι 32 δὲ δὴ Hkl, then Syr., δ’ ἀλλ’ HN.
3 παρ' ἑαυτῶ Ν|4 πυνθάνη H Ι 1 3 προαποφην. H., previously revealed Syr., ἀποφην. N Ι 19 ἀλλὰ γὰρ — 252,32 ἀγωνίζεσθαι &lt; N Ι 19 τοῦ ob richtig? | 21 εὐσεβεῖς Hkl, εὐσεβείας H Ι 22 ταύτους Ηkl, τούτοις Η Ι 23 δι· δασκαλεῖα Hkl, διδασκαλία H, doctrine Syr. | 29 ἥ &lt;
4 nach μείζω ein Buchst, ausrad. H Ι 7 ὁσημέραι, αι auf Ras., H Ι 23 σκέψαι Hkl, consider Syr. σκέψις H Ι 25 αὐτοὺς Wil., αὐτὸς H Ι 26 αἰγυπτίους Nolte, Hkl, αἰγυπτίων H Ι 31 καὶ + (Hkl), and Syr. Ι 33 ἐπινεμόμενος H Ι 35 δεινοὺς H, δεικνὺς N.
8 ὁ &lt; H Ι καθ’ ἄλης τῆς H, ἐπὶ τῆς ὅλης N Ι 12 τε καὶ πυρὸς ἐπιτελ. completed . . with fire Syr., τε προσεπιτελ. HN | 15 παρεσκεύασεν Ν, vgl. 257, 4 u. 258, 20, κατεσκεύασεν H Ι 20 σιδήρεος, ε auf Ras., H, σιδήριος N Ι 24 μάχον H Ι 25 δὲ N, δὴ H Ι 28 οὐδ’ ἄν + WiL, and that which is (as) nothing, is likewise inoperative Syr. Ι 30 ὑπολειφθείη H.
6 εἴποι ἂν εἶναι H, εἶναι εἴποι N Ι τὸ γὰρ H, εἴγε τὸ N Ι 7 οὐκ εἶναι Wil., οὐκ ἄν Η 00&lt; N Ι τι δύνασθαι ∾ N Ι οὔτ' — οὔτε Hkl, οὐδ’ — οὐδὲ HSS Ι 10 ἔργα ∾ N Ι ἦ Hkl, εἰ HN Ι 19 οἱ Hkl, οἵ τινες HSS Ι 20 ἀνυμνούμενοι H, ἦσαν auf Ras.) ὑμνούμενοι N Ι ἀρχὴν Val., rule Syr., εὐχὴν HSS Ι 26 τῆ Hkl, oder τῇ αὐτοῦ θεόμητι Ι συνωμολόγουν N Ι 27 nach τετολμ. + ὁλοσχερῶς ἔσπευδον N, &lt; H u. Syr. Ι 28 ἁγίοις N, pure Syr., ἁγίων H Ι 30 κοσμίως H Ι 32 Val., καθιερώσθαι HSS.
3 παρ' ὧ H Ι lieber τῆς ἐπωνυμίας V al., παρὸ — ἐπων. &lt; Wil. Ι 4 οὖν N, Syr., &lt; H Ι 5 τόσην H Ι 6 ἤγειρε N Ι 7 οὔτὸ in N ὸ vielleicht aus ὼ Ι 8 τὸ δὴ H Ι τῶν + am Rande H, &lt; N Ι θεομάχον N Ι 15 θεοῦ Hkl, Θείου HSS Ι 18 δ’ &lt; 20 βίον, aber ν aus υ, N Ι nach χρῆσθαι + am Rande ἐδίδαξε N Ι 26 δίκη μὸν Val., the eye of justice Syr., δίκην ὀφθαλμῶν ΗΝ Ι 27 τε + Wil. &lt; H Ι 28 δικαίου Hkl, δικαίω H, ς über der Zeile, δικαίως N Ι σώφρονος σωφρόνως HN Ι δεῖν H, ζῆν auf Ras. aus δεῖν N Ι βίου &lt; Ν, that duty to be careful aa to the life of rigtheousness and tem | ἐπιμέλεσθαι Ηkl | 29 θεοσεβείας, σεβει auf Ras., H Ι 30 ὁ δὲ H. ἁ (au
Hkl, Syr. to that of rule (,,in potestatem“) Ι 26 τὸ δὲ HSS, οἷον δὲ τὸ Hkl | nach καταβεβλημένα + ὅσον εἰς ἀπόδειξεν ἐναργῆ τῆς αὐτοῦ θεότητος, Ν, &lt; H
2 ἐσχάτους H | 4 xam H, ταῦθ’ N Ι 6 u. 12 ὑπερβάλοιτο, aber das zw, ausradiert, H | 12 τὸν + Val.(?) Ι τῶν aus τὸν N Ι 14 οὕτος H Ι 17 μὴν &lt; H Ι συνδραμουση H | 24 Wortfolge λόγου τοῖς ἔθωεσιν N | 25 τὰς ἐναργεῖς ἀποδ. N, the open proofs Syr., τῆς ἐνεργείας ἀποδ. H | 26 τὰς &lt; (?) Wil. | 27 καὶ H (u. Syr.), &lt; N Ι 30 ὁ ἡμέτερος H, ἡμῶν N Ι ὅτε H Ι 31 πέμηνεν aus υκ N, has appeared Syr. Ι 33 ἤκουσται, aber ται aus ε, N. Eusebius I.
1 πρόξενα &lt; Ν | 5 ἄνθρωπος &lt; Christoph., Syr. Ι 9 λατρείαν auf Ras. 10 nach Ἑλλ. + τε H Ι 14 κριτῶν H Ι ἀπὸ περάτων &lt; u. ὡς (statt ἴως HSS) Hkl, as to be called throughout the whole creation Syr. Ι nach ἀνθρώπων ungef. 10 Buchst, ausradiert in H Ι 15 nach ἀναγορ. + παρασκεύασας N, &lt; H u. Syr. 16 τίς &lt; H Ι τοῖς N, οἶς H Ι τοῖς über der Zeile N Ι 18 ταὐτὸ N Ι συνόντας H Ι οὐ τὰ H, αὐτὰ H Ι 28 καὶ ἒν μόνον τὸν βροτὸν ἀνθρώπων ἐνηνοχέναι καὶ Η corrupt!, at any period too it must be a singular thing (which) He brought to this world of mankind and Syr. Lee bezeichnet den Syrischen Text als sehr dunkel u. wahrsch. verdorben; Tallqvist: „et ab aeternitate hoc miraculum in mundum hominum duxit"(?) Ι 28 ἐξ αἰῶνος + hier u. Ζ. 29 μόνον ἐξ αἱ. &lt; κόσμον Hkl βροτόν HSS | καὶ &lt; Hkl u. Wil.; ganz ürlich: καὶ ἕν μόνον ἐπὶ τῶν βροτῶν ὤφθη γένους τὸ ἀνθρώποις ἐνηνοχέναι τὰ τοιαδὶ N .
