@config
@_book=De laudibus Constantini
@author=Eusebius
@availableStructure=chapter,section
@compiler=Ernst Boogert
@edition=Eusebius Werke, Ivar A. Heikel, Eusebius, J.C.Hinrichs'sche Buchhandlung, Leipzig, 1902, Vol. I, Internet Archive.
@editor=Ivar A. Heikel
@fmt:text-orig-beta-plain={beta_plain} 
@fmt:text-orig-full={orig} 
@fmt:text-orig-lemma={lemma} 
@fmt:text-orig-main={main} 
@fmt:text-orig-norm={norm} 
@fmt:text-orig-plain={plain} 
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=Available under a Creative Commons Attribution-ShareAlike 4.0 International License
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@sectionFeatures=_book,chapter,section
@sectionTypes=_book,chapter,section
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@structureFeatures=_book,chapter,section
@structureTypes=_book,chapter,section
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:tlg2018.tlg022.opp-grc1
@valueType=int
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:35:43Z

