@config
@_book=Homiliae In Lucam
@author=Origenes
@availableStructure=homilia
@compiler=Ernst Boogert
@edition=Origenes Werke, Max Rauer, Origenes, J. C. Hinrichs'Sche Buchhandlung, Leipzig, 1930, vol. 9, Internet Archive.
@editor=Max Rauer
@fmt:text-orig-beta-plain={beta_plain} 
@fmt:text-orig-full={orig} 
@fmt:text-orig-lemma={lemma} 
@fmt:text-orig-main={main} 
@fmt:text-orig-norm={norm} 
@fmt:text-orig-plain={plain} 
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=Available under a Creative Commons Attribution-ShareAlike 4.0 International License
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@sectionFeatures=_book,homilia
@sectionTypes=_book,homilia
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@structureFeatures=_book,homilia
@structureTypes=_book,homilia
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:tlg2042.tlg016.opp-grc1
@valueType=int
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:39:57Z

