@node
@_book=Acta Archelai
@author=Hegemonius
@availableStructure=chapter
@compiler=Ernst Boogert
@description=open tag without further specification. See the name of the .tf-file for it's meaning
@edition=Hegemonius Acta Archelai, Charles Henry Beeson, Hegemonius, J. C. Hinrichs, Leipzig, 1906, Internet Archive.
@editor=Charles Henry Beeson
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=Available under a Creative Commons Attribution-ShareAlike 4.0 International License
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:stoa0146d.stoa001.opp-grc1
@valueType=str
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:41:22Z

2545	1 animus] animose M | stuabat Α | utramnam C | ad eum pergeret] ex se ad eum pergeret C per se ageret ad eum Μ p. s. ad eum ageret M2 | 3 ingressum A | aliquid M | 4 versutioribus] es folgt in Α eine Ras. von drei Buchst. 5 adda &lt; C | qui . . . instructus] vielleicht eine Glosse zu adda | Τύρβων Epiphanius | addam] adda Α | 6 acceptam eam die beiden m—Zeichen durchstrichen C2 | 7 manen Α manne C | praeceptum fuerat ~ C | 8 curso Α | 9 et &lt;Α |10 ad &lt; M | 11 intruxerat Α | 12 esset] nach quis in M | 14 ad wie immer Α | ignoratum Α | 15 ipsi Α | adhibendum C | 16 singula cum M ~ M2 | cotidiae Α | adqne wie immer Α | 17 perferre Α | hosptiis Α | 18 indicasse Α | 20 vero] igitur C | marcellus litteras ~ M | legit C | 21 est hoc ~ C | 25 apostolus] s aus m w. e. seh. corr. Α | ihm Α | 26 narh misericordia + et M | 27 dnm nm ihm xpm A
1 διατηρήσειε] Dindorf, διατηρήσει J | 9 μὴ] von Cornarius und Pelavius eingefügt | 17 te a] te de Α et a C | ruina C | de laqueis malignis Α a laqueis maligni C labiis malignis M | 18 amen &lt; C | 20 fidem M | iuxta te recta ratione C iuxta recta ratione M | 21 nach missus + sum Α C | et &lt; Α | 22 scribta wie immer Α | 28 primum M | salate Α | 24 animos] λογισμὸν Εpiphanius | 25 docent dicentes] docentes C | 26 auctorem A | quiquam A | 26/27 ungenaue Übersetzung | καὶ φαύλου des Epiphanius nicht übersetzt: 29 o fili &lt; Μ | 30 indiscraetae Α indiscreta C
3 ἐν] nach den Acta corr. Zacagni | 10 nach υἱὸν + καὶ Oehler | 11 γεγεν- νῆσθαι] γεγεννημένον Routh | 16 freie Übersetzung | dei Α | enim &lt; C | 17 fidem Α | patrum Μ | est] fehlt im Griechischen | 18 in (nach enim) &lt; Α | 19 et domini &lt; Μ | ihm Α | 19/20 umgekehrte Reihenfolge der Sätze des Citates | 20 fructus bonos M ~ M2 | malus Α | 21 deum] aus corr. A dominum C | actum Α | factorum C | et &lt; C | 23 qui de] aus quidem corr. C2 | de &lt; Α | 24 nach filium + et Μ | 25 at] tu Α | plura Μ | 26 atque] quae Μ | 27 non &lt; C | sufficiant M | 28 cognoscis Α | aput Α wie immer | 29 parcere. . festinas] sehr freie Übersetzung
3 initio C | 4 nach honorabilis + uale Α | 5 haec ACM | obsequen- tissimo] das erste e vielleicht a. Ras. C | 6 quae] q, Α | 7 nach conclusus + os M | 8 sibi desiderans dari] uidere desiderans M; vgl. Epiphanius, haer, 66,7 ὸ δὲ Ἀρχέλαος γνοὺς τὴν αἰτίαν καὶ τὴν ἐπιστολὴν ἀναγνοὺς ἔβρυχε τοὺς ὁδόντας ὥσπερ λέων ὡρυόμενος καὶ ξῆλον θεοῦ ἀναλαβὼν ἐπειρᾶτο ὁρμῆσαι μᾶλλον ἕως αὐτοῦ καὶ χειρώσασθαι τὸν τοιοῦτον usw. | 9 procuratum Α procuraturam Μ | 18 a te &lt; ΑΜ | 19 vero] uerum Α &lt; Μ | 21 per epistulam &lt; C | promisti C | 22 scriptam atque &lt; C | tradit M | referendam C | 23 ad eum] illi Μ | 24 nach itineris + ac M | 25 ad illum reuersurum A ad eum reditum C
1 fore] futuram C | unum A | calisto M | 2 praecepit Μ | ilico &lt; M | postridum Α | 3 manem C | repperit] das erste p durchstrichen C | 4 tradit Μ | 5 esse zweimal geschrieben A inuitatum se esse C | 5/6 remorationem non prosperam C vielleicht richtig, vgl. Epiphanius a. a. Ο. Cap. 8 ταῦτα γνοὺς ὁ Μάνης ἐσκέπτετο οὐκ ἀγαθὴν εἶναι τὴν τοῦ Τύρβωνος ἐν καθέξει γενομένην παρουσίαν . . . ὅμως διὰ τῆς ἐπιστολῆς λαβόμενος τὴν πρόφασιν δρομαίως ἦκε πρὸς τὸν Μάρκελλον | 6 praesagus Α  | 7 prorsus &lt; M | descedebat Α descendebat Μ | 8 nach archelai + episcopi C | manis] manen AM mannichei C der Genetiv dieses Wortes kommt nur hier und Z 18 unten vor | 9 studiis] studis Α is a. Ras. Μ | quis et] qui sit Α | 11 παρ᾿ ἐμοῦ] Routh interpungiert nach ἐμοῦ, so auch der Übersetzer der Acta | 17 τοῦτον] Zacagni, τούτων J, τούτων τοῦτον Gataker | 18 de fide manitis (rot) M, s. Einleitung | manis) mani Α maunichei C | 19 exemet A | aeteruns Α | 20 et alterum zweimal gesehrieben A | nach bonuml + et A | autem &lt; C | introducit] intruducit Α aus introducim corr. C2, das m-Zeichen ist durchstrichen und t übergesch. | 21 nomen] lumen Α | alter Α | 22 q, Α | est tenebrarum zweimal gesch. Α | 28 conditio aus condicio corr. A | 24 modo] aus modum corr. Α
5 προβάλλειν] Petavius, προσβάλλειν J | 6 προβεβληκέναι] περιβεβληκέναι nach den Acta corr. Oehler, aber vgl. Epiphanius Cap. 45 καὶ αὕτη δέ, φησί, ἡ θήλεια προεβάλετο τὸν πρῶτον ἄνθρωπον | 13 ζωὴν J | 16 aduersus M | 17 singuli] zu singulis corr. Α | suas] singulas Α | accederit A | ut] at C getilgt und ut übergesch C2 | 19 agnouisset C | ad] a A | superuenire Μ | 20 produxit . . . virtutem] produxit ex uirtute A produxerit et esse uirtutem zυ produxit ex se uirtutem ohne Ras. corr. C produxerit ex se uirtutem M | nach qua + uirtute C | 21 ventus &lt; A | 22 materia] maria Α | inductus C | paratum A C | 23 pugnaturus Μ | aduersus A | at] aus ad corr. C2 | 23/24 principes . . . ei] princeps repugnantese Μ | 24 animam A Μ | 26 orante Α | 27 se] ae Α ea M | 28 duxisset M | 29 deorsum animam ~ C | relinquit A
humoforus C homoforus M das erste o getilgt und n übergesch. von M2 | 22 id est . . . humeris] eine Erklärung des Übersetzers w. e. sch. | umeris C | portans &lt; M | intremescit] mescit a. Ras. A intremiscit Μ | 23 haec A | 24 benignus] benedictus A | suis &lt; A | 25 in &lt; A M | interioris A | quod A M | illam Μ | par erat] parerent A pareret Μ | cohercerent A M | quotiensque C quotienscumque M
6/7 αὔτη . . ὑπόθεσις] fehlt in Acta | 16|17 freie Übersetzung | humero A | 17 et &lt; A | 18 ex sese] ex se A esse se C | vel germina] findet sich nicht bei Epiphanius | furata M | 18/19 a quibusdam principibus &lt; C | 19 principes &lt; M | 21 vinxit] uixit Α iunxit M | eum A | 22 quia] qui A | 23 dilectum &lt; C | salute  A | haec A | 24 humoforum C homoforum Μ das erste o getilgt und u übergesch. von M2 | transformavit] aus transformabit ohne Ras. corr. C | 25 adparebat] parebat A C M nach Epiphanius von Zacagni verbessert | 26 putauerunt C | natum] naturam C | venisset] uidisset Μ | 27 concinnauit C | rotam] μηχανὴν Epiphanius | statuit] status Μ | 28 urceos] os aus Corr. A urchios M | quae] q a. Ras. A | nach quae + rota C | 29 morientum M | quas] quam M | id est sol] eine Erklärung des Übersetzers w. e. sch. | adimens] λαβὼν Epiphanius
1 ταύτας] ταύταις Oehler | 6 οὕτω] w. e sch. las der Übersetzer πάλιν (αὖθις Oehler) | 14 τοῦ] Petavius, τὸ J | 16 tradet A | discus] discursus A | nobis] nauis M | 17 cambas] a. Ras., cymbas übergesch. M2 | 18 luminaria] das erste i aus a corr. Α | impleta Μ | lunam A | transfetare Α | ad] d aus Corr., vielleicht aus b corr. A | 19 apocrisin C apocrysim Μ | facere] patitur C | onere] honore A | reuelata A leuata Μ | 20 cumbas] cumbam C cymbas M das y zu u corr. und y übergesch. M2 | rursum A | urceos] das ο aus u corr. A | 21 animarum] τῆς ψυχῆς Epiphanius | substantiam Α | 23 quod gerit] fehlt bei Epiphanius | 24 permanet M | illa] bezieht sich auf saecula, vielleicht ein Irrtum des Übersetzers; illae Zacagni | 25 vir] der Übersetezer hat ἀήρ und ἀνήρ verwechselt | 26 animarum mundarum ~ C M | 27 mortis . . . causa] a. Ras. w. e. sch. M | hominibus est ~ A | ista] πάλιν αὕτη Epiphanius | 28 et] aus Corr. A | furto. . . . principes] freie Übersetzung | appetit C appetiit M
10 θερισμοῦ Zacagni, vielleicht mit Recht, θεριστὴς Petavius, alter princeps messor appellatus Cornarius | 15 vivente] aus uiuentes corr. M1 | spirito A | educti] seducit zu seducti corr. M2 | 15/17 eine Paraphrase | 15 masculis A | 16 nach adulescentem + se M | 19|20 freie Übersetzung | 19 amoris] amoriis A | excitati] escitati A excecati Μ | 20 calore] amoris calorem Α | ergo] enim C | eis &lt; C | post eam] postea M, fehlt bei Epiphanius | nach eam + anxii effecti fuissent C | 21 subito] fehlt bei Epiphanius | conparuerit] comparuit (uit a. Ras. A) AC | 22 ut M | universum] omnem C | 22|24 wieder eine Paraphrase | 24 princeps] das e aus i corr. Α | nach sudat + ei Α | 25 effundet A | famem] famam A; der Übersetzer hat w. e. sch. λοιμός und λιμός verwechselt | 26 omnem &lt; Α C | mortem A | hoc enim M ~ M2 | 27 magni] imaginis Μ | 28 rursum AC
3 τόνῳ] πόνῳ Petavius | 6 τοῦτο] fehlt in den Acta | 14 εἰς φασήλια] σφασήλια J, φάσηλον oder φασίολον Dindorf | 16 uirginem A | incipiet Α excipit M | excidere . . . cum &lt; C | 17 pestilentia] das erste e aus i corr. A | si &lt; C | 18 radicis] radices Α radicum CM | 18/19 ungenaue Übersetzung | 19 humofori C homofori zu humofori corr. M2 | 20 alia quoqne] πέντε Epiphanius | 21 transferuntur A | purgantur A | parum ex ea M | 23 commisit C ammisit M | elephantiacorum] elefantorum Α elefantia corum C elefantiacorum et cephalorum M; wahrscheinlich liegt eine Doppelversion des Übersetzers zu Grunde | 24 transfunduntur AC | 26 ex materia] ἀπ᾿ ἀρχῆς Epiphanius; die Übersetzung hier ist übrigens nicht genau | 28 eos transfundi ~ Α | fasellum Α fasolum M | 29 aut in spicas &lt; C | dementiatur C
10 Routh und Oehler interpungieren nach ὕδωρ | Zacagni vermutet πλήσσει als die Lesart des Übersetzers | 11 γεέννας] Dindorf, γενεάς J,vgl. 18, 11 | 14 ἔσθιεν am Rande J | 16 manducant C | est &lt; M | nach est + ut C | 16/17 ipsum . . effectum] ipsi manducentur pane effecti C; vielleicht eine Doppelversion des Übersetzers | 17 qui (nach effectum)] quod A | murem] mnre Α | 18 nach etiam + et A | si &lt; A | 21 eum] enim C | perseam] per se eam Α persa C | 22 persea illa] per se a illa zu per se ad illam corr. C2 | quam plantaverat] fehlt bei Epiphanius | 23 dispergitur M | 24 aquam M; vielleicht hat der Übersetzer buchstäblich übersetzt ohne die Construction zu treffen | non &lt; Μ | 25 elementa A εὐσέβειαν Epiphanius | poenis] w. e. seh. aus paenis corr. A | subditar AM | 26 catecumenorum Α cathecuminorum M | facias C | miseri- cordias] εὐσέβειας Epiphanius | 27 est] fehlt bei Epiphanius | illis &lt; C | 28 oratio manicheorum super cibos (rot) Μ | ad panem &lt; Μ
1 σε] fehlt in den Acta | vielleicht ist σε nach den Acta vor ἔβαλον zu ergänzen | 2 nach ἀναιτίως + σε Oehler | 12 τις] τι Routh und Oehler | 14 neque tribulaui C nec te tribulaui Μ | 15 te fecit] ἐποίησε ταῦτα Epiphanius | te (nach detulit)] fehlt bei Epiphanius | nach mandnco + et soluo C | 16 respondit AM | illum qui] eum qui ei C | 17 et ita . . paulo ante &lt; Α | et &lt; M | 18 mola Α | 19 mola Α in molam fehlt bei Epiphanius | aut &lt; Α | 20 ant si] ita et si quis Α aut qui M | nach eos + hoc M | 21 dicunt] fehlt bei Epiphanius | quosdam &lt; A | 21/22 praeter . . mundos] fehlt bei Epiphanius, | 22 nach quibus + in M | occiderit M | 23 obriuntur Α moriuntur M | et illi dicunt] fehlt bei Epiphanius; w. e. sch. ist es ein Zusatz des Übersetzers | illi] ibi Α hi M | 24 movet] leuat AM, vielleicht liegt hier eine Doppelversion des Übersetzers vor | aerem] das erste e übergesch. Α | 25 et volatilium &lt; M | 26/26 et . . mundo] den Zusammenhang hat der Übersetzer verkannt; die Übersetzung ist hier übrigens nicht genau | 26 materia M | 27 ideo] fehlt bei Epiphanius | necesse est illut C
1 δς] Zacagni, οὐ J, Dindorf nimmt mit Unrecht eine Lücke an; vgl. Epiphanius Cap. 54 | 3 ἐκείνων] ἐκεῖνο (mit φυτὸν zu verbinden) Oehler, wοhl mit Reeht | 4 αὐτός] Oehler, αὐτό J; vgl. Epiphanius a. a. Ο. | nach Ἰησοῦς + καὶ Zacagni, Oehler und Dindorf, ober vgl. Epiphanius a. a. Ο. | 13 ὑμῖν] υ aus η hergestellt J ἡμῖν Petavius; vgl. 19, 9, | 14 πνεῦμα] πνεύματα Oehler, wohl mit Recht; viellcicht liegt eine Verwechselung der Abkürzungen vor | 15/16 ungenaue Übersetzung | paradisi Μ | nach mnndus + et C | 16 concupiscentia M | agitationes C | 17/18 qua agnoscitur] quo cognoscitur Α | 18 est Iesus] estis C. Der Schreiber hat dic Abkürxung IS = Iesus verlesen | eius] illius C | 19 bono A | 20 dei] deus aus dei corr. M2 | parte] r übergesch. Α &lt; C | materia C | plasmatur Μ | 21 hominem A | ipsut A ipsum Μ | 22 luna C | animam Α | 38 tradetur Α | gehenna] das erste e übergesch. Α gehennam CM | 24 postquam Α | correpta] correptam Α correcta Μ | transfundetur M | alia] fehlt bei Epiphanius | 26 illud Μ | 27 qui ΑΜ
1 τοῖτο] der Übersetxer hat τούτων gelesen | 2 nach ἐλάλησαν + ἐν ἀληθείᾳ Zacagni mit Recht | 9 ὑμῖν] Cornarius und Zacagni, vgl. 18, 13; ἡμῖν J | 14 καὶ (nach δεῦτε)] fehlt in den Acta und bei Epiphanius Cap. 56 | 15 a #x003C; Α | deceptio Α | in] i übergeseh. Α | 16 mentes C | illorum Α | et si . . . ipsorum #x003C; M | 17 morientur Μ | seculo M | deuictus Α | non #x003C; Μ | 18 paraclyti Α wie immer, paracliti M wie immer | non #x003C; A | 19 desinerint Α | orarent et] orantes M | 20 oleum super caput CM | extorcidiatum Α exorcizatorum suorum M | 21 horum C | mihi] hi übergesch. Α | 22 enim] autem C | nominibus] fehlt bei Epiphanius | hoc #x003C; Α | 23 magnum . . nomen] magnum esset honorabilem nomen Α | ille dicit] fehlt bei Epiphanius | natura Α | esse] aus esset gleich corr; Α | 24 partam M | inquid Α wie immer; fehlt bei Epiphanius | 25 concupiscentia Α | 26 quia qui dicit #x003C; Α | 27 et (nach nostram) #x003C; CM
1 ἤ] et dic Acta | 3 nach μορφὴν + καὶ Routh | 4 ἔκτισε] ω. e. sch. zu ἔκτισαν zu corr., so Cornarius | 18 uidemus Α | qui] quia A | 18/20 nicht wortlich übersetzt | 20 accipimus Α | 21 uidemus Α | 22 creaverunt] fecerunt Μ | nach creaverunt + qui Α | euuam Α | 23 per haec] διὰ τούτων Epiphanius, per hos Cornarius | esse Α | 24 mundum C | conditionis M | nach vero + dicit M | patrem Α | 25 eo C | in*itio Ras. von einem Buchst. Α | 26 aborta A | haec Α | 27 mittet C | 27/28 id est] fehlt bei Epiphanius | 28 nach est + per C | omnes Α | rapatur Α aptatur Μ | 29 moysen Α | 31 gentes C
17 moysen Α | 18 quoniam Μ | 21 feceris AM | humoforus C bomoforus M | 22 derelinquet Α reliquid M | 28 consummat A | dimittur anima Α | statt animam βῶλον Epiphanius | 23/24 quae obicitur] fehlt bei Epiphanius | 24 uincantur AM | 25 fiet A | statua venerit] Beausobre, ista tota uenerit Α statuta uenerit dies C statuta uenerit probatio Μ | prolationes] probationes AM | 26/80 eine ziemlich ungenaue Paraphrase | 26 modica] od a. Ras. C | uita C 27/28 maiori in navi] maior in naui Α maiori naui CM | 28 navi vivens] a. Ras. M | ignis illius ∾ C | 29 et aquae] ea quae C | et #x003C; Α | ignis vivi quae] ignis uiuensque Α uiui quae C | 30 habitabant Μ | obsumat Α | quod AC
