@config
@_book=Commentarii in Evangelium Joannis
@author=Origenes
@availableStructure=book,section,fragment
@compiler=Ernst Boogert
@edition=Origenes Werke, Der Johanneskommentar, Erwin Preuschen, Origenes, J. C. Hinrich'sche Buchhandlung, Leipzig, 1903, vol. 4, Internet Archive.
@editor=Erwin Preuschen
@fmt:text-orig-beta-plain={beta_plain} 
@fmt:text-orig-full={orig} 
@fmt:text-orig-lemma={lemma} 
@fmt:text-orig-main={main} 
@fmt:text-orig-norm={norm} 
@fmt:text-orig-plain={plain} 
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=Available under a Creative Commons Attribution-ShareAlike 4.0 International License
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@sectionFeatures=_book,book,section
@sectionTypes=_book,book,section
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@structureFeatures=_book,book,section,fragment
@structureTypes=_book,book,section,fragment
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:tlg2042.tlg005.opp-grc1
@valueType=int
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:41:06Z

