@config
@_book=Historia Ecclesiastica
@author=Eusebius
@availableStructure=book,chapter
@compiler=Ernst Boogert
@edition=Eusebius, Kirsopp Lake, Eusebius, William Heinemann, G.P. Putnam's Sons, New York, London, 1926, I.
@editor=Kirsopp Lake
@fmt:text-orig-beta-plain={beta_plain} 
@fmt:text-orig-full={orig} 
@fmt:text-orig-lemma={lemma} 
@fmt:text-orig-main={main} 
@fmt:text-orig-norm={norm} 
@fmt:text-orig-plain={plain} 
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=Available under a Creative Commons Attribution-ShareAlike 4.0 International License
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@sectionFeatures=_book,book,chapter
@sectionTypes=_book,book,chapter
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@structureFeatures=_book,book,chapter
@structureTypes=_book,book,chapter
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:tlg2018.tlg002.opp-grc3
@valueType=int
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:36:16Z

