@config
@_book=Historia ecclesiastica
@author=Eusebius of Caesarea
@availableStructure=book,chapter,section
@compiler=Ernst Boogert
@edition=Eusebius, The Ecclesiastical History, Vol 1-2, Eusebius of Caesarea, Kirsopp Lake, J.E.L. Oulton, H.J. Lawlor, William Heinemann; G.P. Putnam's Press; Harvard University Press, London; New York; Cambridge, Mass, 1926-1932.
@editor=Kirsopp Lake, J.E.L. Oulton, H.J. Lawlor
@fmt:text-orig-beta-plain={beta_plain} 
@fmt:text-orig-full={orig} 
@fmt:text-orig-lemma={lemma} 
@fmt:text-orig-main={main} 
@fmt:text-orig-norm={norm} 
@fmt:text-orig-plain={plain} 
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=not provided by source
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@sectionFeatures=_book,book,chapter
@sectionTypes=_book,book,chapter
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@structureFeatures=_book,book,chapter,section
@structureTypes=_book,book,chapter,section
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@valueType=int
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:36:25Z

