@config
@_book=Selecta in Deuteronomium
@author=Origenes
@availableStructure=paragraph
@compiler=Ernst Boogert
@edition=Origenis Opera Omnia, Patrologiae cursus completus (series Graeca), Charles Delarue, Origen, J. P. Migne, Paris, 1862, 2, 12, Internet Archive.
@editor=Charles Delarue
@fmt:text-orig-beta-plain={beta_plain} 
@fmt:text-orig-full={orig} 
@fmt:text-orig-lemma={lemma} 
@fmt:text-orig-main={main} 
@fmt:text-orig-norm={norm} 
@fmt:text-orig-plain={plain} 
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=Available under a Creative Commons Attribution-ShareAlike 4.0 International License
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@sectionFeatures=_book,paragraph
@sectionTypes=_book,paragraph
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@structureFeatures=_book,paragraph
@structureTypes=_book,paragraph
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:tlg2042.tlg053.1st1K-grc1
@valueType=int
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:40:16Z

