@node
@_book=Sententiae = (Carmen morale XXX)
@author=pseudo-Menander, Gregory Nazianzus
@availableStructure=sentence
@compiler=Ernst Boogert
@coverage ratio=100.0%
@description=the lemmatized form of the text tries to return as much as possible the words as a comma-separated list of possible lemmata. If no lemma could be found, the word is preceded by a "*". The lemmata have been defined by using the normalized text
@edition=pseudo-Menander, Die arabische Überlieferung der sogenannten Menandersentenzen, Manfred Ullmann, Wiesbaden, Kommissionsverlag Franz Steiner, 77-80, 1961.
@editor=Manfred Ullmann
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=Available under a Creative Commons Attribution-ShareAlike 4.0 International License
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:tlg2022.tlg060.1st1K-grc1
@valueType=str
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:39:17Z

ἀρχή
ἅπας
καί
τέλος
ποιός,ποῖος,ποιόω,ποιέω
θέω,θεός
βίος,βιάω,βιός,βιόω
ὁ,ὅς
κέρδος
εὖ
βιάω,βιόω
κατά
ἡμέρα,ἥμερος
γιγνώσκω
πάντῃ,πᾶς
ὁ,ὅς
καλέω,κάλως,κᾶλον,κήλη,καλός,κάλη
ὁ,ὅς,τίς
δρᾶμα
δεινός
πένομαι
χείρων
δέ
εὐπορέω
κακόω,κακός
εὐεργετέω,εὐεργέτης
νομίζω
μιμέομαι
θέω,θεός
ζητέω
θεάομαι,θεός
σύ,σέω,σός
χρηστότης
χρηστός
εἰμί,οὖν
ὁ,ὅς
σάρξ
κρατέω
καί
δαμάζω
καλός,κάλως
θυμός
χαλινόω
μή
φρήν,φρενόω
ἐξίημι,ἔξεστι,ἔσσομαι,ἔξω
πίπτω
ἱστάω,ἵστημι
μέν
ὄμμα
γλῶσσα
δέ
σταθμάω,στάθμη
ἔχω
κλείς
οὖς
κεῖμαι
μηδέ
πορνεύω
γέλως
λύχνος
βίος,βιάω,βιός,βιόω
σύ,σέω,σός
πᾶς
ἡγέομαι
λόγος
μή
σύ,σέω,σός
ὁ,ὅς
εἰμί,εἶτα
ὁ,τίς,τις,τῷ,ὅς
δοκέω
ὑπορρέω
νοέω
ὁ,ὅς,τίς
πάντῃ,πᾶς
πράσσω
δέ
ὅς2,ὁ,ὅς
πράσσω
θέμις
ξένος
σεαυτοῦ
εἰμί,οἶδα
καί
τιμάω,τιμή
ξένος,ξενόω
ὅστε,ὅτε
εὐπλοέω
μάλιστα
μιμνήσκω
ζάλη,ζαλάω
πάντῃ,πᾶς
εὐχάριστος
δέω2,δέω1,δεῖ,δέω
δέχομαι
ἐκ
θεάομαι,θεός
ῥάβδος
δικαιόω,δίκαιος
πλέως,πλείων,πλέω,πολύς
τίη,ἤ2,ἤ
τιμή
κακόω,κακός
σοφόω,σοφός
θύρα
ἐκτρίβω
πλούσιος
δέ
μή
ὁ,ὅς
μικρός
οὐ
μικρός,σμικρός
ὅταν
ἐκφέρω
μέγας
φυλάσσω,φυλάζω
σεαυτοῦ,σαυτοῦ
πτῶμα
δέ
ἄλλου,ἄλλος
μή
γελάω,γέλα
χάρις
φθονέω
ὁ,ὅς
φθονέω
δέ
αἶσχος
μέγας
ψυχή
θύω1
μᾶλλον,μαλλός
τίη,ἤ2,ἤ
ὁ,ὅς
πάν,πᾶς
θεάω,θεός
ὦ
τις,τίς
φυλάσσω,φύλαξις,φυλάζω
οὗτος
καί
σώζω,σῴζω
