@node
@_book=In Jeremiam (Homiliae 1-11)
@author=Origenes
@availableStructure=homilia,section
@compiler=Ernst Boogert
@description=open tag without further specification. See the name of the .tf-file for it's meaning
@edition=Origenes Werke, Erich Klostermann, Origenes, J. C. Hinrichs'sche Buchhandlung, Leipzig, 1901, vol. 3, Internet Archive.
@editor=Erich Klostermann
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=Available under a Creative Commons Attribution-ShareAlike 4.0 International License
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:tlg2042.tlg009.opp-grc1
@valueType=str
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:40:51Z

25620	Überschr.: Ἱερεμίας S fol. 208v; Πότε — Ὁμιλία α΄ nach Η: Quo tempore Hieremias exorsus est prophetare et sich quihus principihus prorhetavit et infra quae dicta sunt ei α Domino | 5 λέγει] Scorr. λέγη S* + ἀεὶ Blass Lietzmann nach Η: semper | 7 ἀρκεῖ nach H: sufficiunt προσάξω μόνον Co τὰ übergesch. Scorr. | 11 ἠθέλησε σιωπῶν z. Τ. mit Ru ἔθελε σιωπῶν) nach Η: noluit cum silentio ἠθέλ] εἰπὼν S | 12 Hebraeorum Η | 17 αὑτῶν Blass Diels. αὐτῶν S.
3 ἕπονται] ἕψονται Blass | 3 ἑαυτῶν τε ἅμα καὶ Blass AVilamowitz nach Η: suam pariter et | 7 μὴ] &lt; | 8 μηδὲ] et H; beide Negationen verwirft auch Hu | 9 ἱστορία ἐστὶν καὶ ἀναγέγραπται] historia superscripta est Η | 12 ἕως SH aus Ζ. 15. 17 eingedrungen | 16 καὶ] + legens Η (vgl. Ζ. 11) | 34 τῆς προφητείας Co propJtetiae Η τῆς προφητεύει S τίς Προφητεύει S üngere Corr.
8 παρέδωκα nach Η: tradidi παρέδωκε S (Hom. 18, 14: παρέδωκα) | 11/12 οὐκ ἀναιτίως δὲ οὐ u. θεοῦ οὓς ἐχκατέλιπε S and. Hand w. e. seh. | 13 φέρει S* φέρῃ S1 | 22 πιστεύωμεν Co πιστεύομεν SH | 27 ἐξαίρετον] vgl. S. 4, 3 9, 12; oft mit τι verbunden: in Matth. Tom. 13, 2 (Lo 3, 212), Exhort. 14 (Orig. I, 14, 7).
14 ἂν ἐναργῶς Diels Wilamowitz ofiose Η (= ἀγρῶς Ru) | 19 ff. (bis Hom. 1, 7 oder weiter?) Hierzu Fvagm. 2 in C: Ταῦτα — κρείττονα | θλίβει — ἑρμηνείαν nach H: de Hieremia difflcilem faciunt interpretationcin.
1 ἐστὶν] est . | 3 οὖν] huic Η | 4 τῷ σωτῆρι] &lt; Η | 5 αὐτὸ οὐ Blass | 6 ὅτι] + ὥς Blass | 7 αὐτό] αὐτόν Co, Η w. e. seh. | 8 δ᾿ οὐ δοκεῖ δυσωπεῖν nach Η: autem facili intellectu . . referuntur | 9 εἰπεῖν Hu Dicere Η εἶπον S | 13 ἐπεὶ — Χριστοῦ mit Η: quoniam minora sunt | 16 ὅλως V | 25 τροπολόγει Co allegorizet Η τροπολογεῖ S | 26 τὰ] ς· τὰ S κατὰ τὰ Hu nach Η: per | 28 καὶ2 übergesch. S1 30 ἐφαρμόσαι τῷ Ἱερεμίᾳ streicht Wilamowitz | 32 ἁρμόζοντα τῷ σωτῆρι] super salvatore, quasi de eo (od. deo) sint scripta H.
9 καὶ τὸ mit H: et hoc quod dictum est | 11 ἢ Co quam Η μὴ S | 16 ἄπιθι πονηρία S | 22 ἑαυτόν] + formam servi accipiens Η | 30 ἄπιθι πονηρία S (vgl. Ζ. 16) | καὶ ἃ mit Η: et ea quae τοῦτο Co | 32 εἰ καὶ mit Η: etiamsi εἶτα S εἰ Co.
1 οἶδεν S nesciat Η οἶδα Co | καὶ| — τοιοῦτο] et cetera huiusmodi quae maiora (od. minorci) sunt Η | 5 λέγεις οὐκ ἐπίσταται nach Η: audes dicere quia nesciat λέγει οὐκ ἐπίσταμαι S | 20 γὰρ streicht Blass &lt; Η | 23 ὥστε εἰπεῖν] zu streichen? | φωνῇ? Blass | 24 ἢ ἄλλων mit H: sive reliquorum (od. reliquorumque) | 26 οὐκ ἐπίσταται nach Η: ideo nesciat | 80 ἐρεῖς] intellegis Η (= ὁρᾷς?).
12 καὶ Co et Η | 15 u. 16 τοῦ θεοῦ] &lt; Η, nach Hu mit Recht | 17 εἰμι1] + καὶ εἶπε κύριος πρός με Co | μή — εἰμι mit Η: Noli divcre: Juvenis ego sum | 19/20 δίδωσιν — λόγους2] ut det eiverha Η | 21 τῷ] vgl. Ζ. 6 | 23 ἐκριζώσεως] + Sed nunc accipit (od. accepit) ijarva, desercns maiora paid isper Η vielleicht richtig.
5 ὅρα Co ὁρᾶν S intelligere H (l. intellege?) | 6 καὶ πλάσεως nach H: et plasmationis und c. Cels. (s. ob.) | εἴτε πρὸς τὸν1] πρὸς τὸν εἴτε S | 8 γίγνεται S | 11/12 πρὸς—γάρ] &gt; Η w. e. sch. | 12 οὐκ ἂν] quomodo H | 18 ἐπιστώμεθα Hu ἐπιστάμεθα S | 19 τί δὲ nach H: quid arbitraris εἰ δὲ S | 21 θεοῦ] + sed ipsi faciunt ut ignorentur H, wohl Ausschmückung | 21/22 καὶ—τηλικοῦτος] Η scit prophetas et si quis H | 25 ἄλλον Ru nach H: alium.
10 ὅτι] cum Η (= ὅτε) | τοῦ Ἱερεμίου] vgl. Ζ. 8 de Jeremia Η τὸν ιερεμίαν S Ι 20 ὑμῶν nach Η: vestris | 25 προφητεύῃ Ru προφητεύει S | 30 οὓς ἐὰν Lo quoscumque Η.
6 ἐὰν nach S. 4, 12 ἂν S | 10 οὗ Hu nach H: cujus rei | 15 ἕνα ἄρτον nach LXX cod. 88 vgl. auch H: panem, τ`` [??] ἀρτίων S μόλις ἄρτον Co | 19 πάντως SH πάντας? Blass vgl. II Tim. 3, 12 | 21 πάντα] + quae (od. quae eis) praecepta sunt H.
5 τὸ δὲ ἓν] neque unum H; hiernach Hu: μηδὲ ἓν, Blass: οὐδὲ ἕν; aber man müsste dann auch bei Orig. etwas freier behandelt zu sein, während H in der Übers. wie im Comm. genauer ausmalt | 6 ἐπεὶ δὲ] mit H: autem quia (od. quia iam) ἐπειδὴ S | 13—S. 14, 30 Hierzu Fragm. 3 in C: Μακάριον—ποιήσω | ὡς Hu nach H: ut ὃς S Co (der vorher οὗτος liest) | ἃς] + Christo H | 18 ἐκριζοῦν Lo eradicare H | 18/19 οὐδὲ —ἔθνη nach H: Nec potest aliquod regnum dici, nisi quod sub se continet nationes | 19/20 βασιλεία2—ἐστὶν] S w. e. sch. lückenhaft regnat fornicatio in homine peccatore, necesse est ut regnum fornicationis habeat gentes suas H | 21 αὐτὸ τὸ mit H: Ipsum illud | 21/22 ἀποστερήσεως — ἁμαρτημάτων] fraudis, quo vix aliquis immunis est, habet regnum suum, et sub regno uno multas possidet gentes, per plurimas scilicet species avaritiae.
1—4 εἶτα—ὀργήν] et ob id H | 3 τῆς1 V τὴν S | 8 ἐν vgl. S. 36, 21/22 | τῆς ψυχῆς vermutet Hu | 10 πορνεῖαι mit C: μοιχεῖαι, πορνεῖαι καὶ τὰ λοιπά und H: fornicationes τὸ ἐκριζωθέν nach H: adhuc permanet quod evulsum est.
5 δεσμάς2] ΗCo; doch vgl. Manich. ap. Epiph. 66,65 | 10 ὁμοίως τῷ Hu juxta quod scriptum est Η ὁμοίως τὸ S | 11/12 Subversum est aliquid, lapides quoque ipsi qui destructi sunt conterantur, ne . . . . assumi valeant Η | 11 τι Blass vgl. Η δέ S | 12 τὴν streicht Blass | 15 τοῦτο] + jubet Dominus Η | κατακαύσατε Co H κατακαύσαται V καταπαύσατε S | 16/17 Η kennt nur ein ἀπόληται w. e. seh. | 24 τὸ »οἰκοδομεῖν mit Η: aedificant (vgl. S. 4, 24. 26 geg. S. 15, 14) | 27/28 οὐκ — ἀποκτενῶ mit Η: Νοn dixit (+ prius Vall.) Ego uiuificabo, et postca, oceidam.
3 νόμου] + et Prophetarum Η | λέγει Co dicit Η λέγοι S | 4 ἐπαγγελίαν] adnuntiationem Η ἀπαγγελίαν S | 4/5 οὐ βλέπεις . . . . ἢ οὐχ ὁρᾷς] non advertentes . . . . non considerantes Η | 15 ἀφαιρεθῆναι (vgl. Hu) nach H: auferantur ῥηθῆναι S | 17 τίς] aut (od. et) quae Η | 19 οἱ — ἄλλως (z. Τ. mit Blass) nach H: sermones Dei aedeficent atque plantent. Possumus siquidem et aliter οἱ λόγοι οἰκοδομηθῶσιν· οὐ δύναμαι γὰρ ὅλως S.
1 ἀλλ’ οὐ τὰς βασιλείας nach Η: sed non regna | 6 εἴ τις ἀκολασία; οὐκ ἔστι κατασκάπτουσα, εἴ που εἰδωλεῖον] si qua luxuria, si qua discordia non est suffossa. Sicubi idolum Η | 10 οὐκ ἄλσος] non infertilis, sive lucus exsurgens Η vgl. S. 27, 7ff. | paradisi Η παραδείσου Hu | τοῦ θεοῦ] &lt; Η | 14 μέχρις S | 14/15 ἐὰν — &lt; Η | 17 Homilia ΧΙΙΙ Η | 18 — S. 17, 10 Hierzu Fragm. 5 in C: Εἰ—Σιών | ὁλέθρου] mortis Η | 21 ὑπερβὰς] ὑποβὰς Blass | τὸ ῥητὸν ἐρῶ] reperio Η τὸ ῥητὸν εὐρίσκω Hu | οὖν] &lt; Η ὁ Ru | 23 ἄριστον CRu ἀρεστὸν S ἀρετὴν Co Η | 24 ἐκτίσαμεν SC adtraximus Η ἑλκήσαμεν Hu [sic].
1 προφήτῃ] + nunc queritur Deus et Η | 5 τίς Co qua (causa) Η | 14 τῆς2] τοῦ Hu vgl. imagine Zahuli H, doch übers. Η d. ganzen Abschnitt sehr frei | χείρνος] + imde debemus magnorere laborare, ut quomodo H, was vielleicht einzufügen | 16 πλὴν] ad quam Η καθ’ ἣν Hu unter Streichung von κατ' εἰκόνα (so las man statt ἐν εἰκόνι) τοῦ ἐπουρανίου | 19 γὰρ] autcm Η | 24 οὐδὲ — ψευδῆ] et mendacetn ex parte plantavi Η.
10 γραφῆς S Sacra volumina Η τροφῆς? Blass | 13 δίστομον] + ef reliqua Η | 15 ἔστι Co ἔστη S | 16 ἐπεὶ δὲ] ἐπειδὴ S | 18 δεόμενα] + facili curafione nee Η | —20 πρὸς — πόᾳ] &lt; Η | 20 πόᾳ Co παρὰ S | 28 λόγου νίτρου, λόγου poamnitrique sermonem H.
1 πνεύματι mit H: spiritu u. Hom. 14 in Luc. | 1 — 7 Η frei: Si peccasti, et peccatorum. sorde pollutus es, lavabit Dominus sordes filiorum, et filiarum Sion, et sanguinem emundahit de medio eorum. Si aiitem mortale peccatwn est, nonpossumus nitro poaque mundari et spiritu judicii sed spiritu combustionis et poenae | 5 πρὸς2 — καύσεως Blass | 10 καὶ streicht Co | 11 ἁγίῳ καὶ CoH καὶ ἁγίῳ S | 18/19 ἄνθος — δικαίους nach Η: flos justis | 21 μακάριος Co heatus Η μακαρίοις S.
2 ἐπὶ] &lt; V | 5 ἀποτιθώμεθα Ru reponamus Η ἀποτιθέμεθα Scorr. ἀποτιθόμεθα S* W. e. seh. | 6 ἐὰν δυνηθῶμεν] ut . . . si fieri potest Η ἵνα δυνηθῶμεν Co | 8 ἀγαθοῖς] scmcfis Η | 18 f; GhCo ἡ S | τί Blass ὅτι S | 26—S. 28, 2 Fragm. 6/7 in C: Καθόλου — δικαίων.
4 κατὰ τὸ σῶμα] fast unleserlich (vgl. TU NF 1, 3, 16 Anm. 4) in S, ätigt durcb C: ἐν τῷ σωματικῷ | 5 ἔχει S | 10 αὐτὸς C αὐτοῖς S | 20 κυριευθησόμεθα. ὁμιλία γ΄ S. Dass die Homilie verstümmelt ist, beweist abgesehn von das plötzliche Abbrechen und das Fehlen der Schlussdoxologie. In C Frgm. 67 folgt auf ἄνδρα Ζ. 16) noch: Φησὶν οὖν ἐντρεπτικῶς· μὴ τοῖς εἰδώλοις ὁμοίως ἀνόνητος αὐτοῖς γέγονα, οῠ χάριν τὴν ἐμὴν ἀπέδρασαν δεσποτείαν; καίτοι καὶ ἀποστάντες ἐμοῦ κόσμου καὶ δόξης ἑαυτοὺς ἀπεστέρησαν· δόξα γὰρ αἰώνιος ὑπὲρ κεφαλῆς τῶν δικαίων. Doch hat dies bedenkliche Ähnlichkeit mit Theodoret Comm. in Jerem. 2, 31 MPG 81, 513: Εἰρωνικῶς ταῦτα λέγει. Ἆρα, φησὶ, μὴ τοῖς εἰδώλοις εἰμὶ παραπλήσιος; ἆρα μὴ ὁμοίως ἐκείνοις οὐδένα αὐτοῖς καρπὸν ἀγαθὸν προσενήνοχα, καὶ διὰ τοῦτο τὴν ἐμὴν δουλείαν ἀπέδρασαν;
4 Homilia ΧΙΙΙΙ Η | 7 οἰκοῦν Co Εἰ οὖν Ἐ konig. aus T?) V | 8 λαὸς] + post Salomonis interitum Η | 11 Ἰσραήλ, Ἰούδα Co Η Ἰούδα, Ἰσραὴλ S | 14 πρῶτον Ru nach Η: primus πρὸς τὸν S (vgl. S. 26, 6) | 22/23 κατηγορεῖ — φησιν) Accusatur Israel et dicitiir Η | 26 οὐκ ἐπαιδεύθη] Που egit pocuitentiam, nec conrersa est ad mc Η | 27 τοῦ Co τώ S | 29 προφητεῦσαι + ad Israel H, wohl richtig.
1 Ἰσραήλ] · ·ἐιτ ABBREV S Ἰσραήλ· εἶτα Co | 4 μέλει] μέλλει S | 7 — 8. 28, 20 Hierzu Fragm. 9 in C: Λύ)ζει — ἀνέξεται | 8 ἐποίησάν μοι] fecit mihi Η ἐποίησέ μοι Ru | 9 »Ἰσραὴλ« πρῶτον mit Η: lyrius Israel Ἰσραήλ. Πρῶτον S | 10 ἐκεῖ mit Η: illie U. LXX | 11 καὶ οὐκ ἀνέστρεψε Co vgl. LXX et non est conversa Η | 13 ὡν] &lt; Η w. e. seh. | 15 δέον παιδευθῆναι τὸν Ἰούδαν] &lt; Η | 16 τὴν συναγωγὴν Ἰσραήλ] &lt; Η | 19 ἐποίησα] ἐποίησε S passa est Η | ἀποστασίου] + in manus suas Η.
2 γέγονε] + quodammodo Η | τῆς Ἰσραὴλ συναγωγῆς] vgl. S. 23, 22 ejus Η | 3 οὖν] &lt; HLo | 5 ἡ κλῆσις nach Η: vocafio (jentiuni ἢ κἆν εἷς S κἂν εἰς Co κλῆσις Hu | 7 τῆς σωτηρίας] &lt; Η || 11 ἐγκαταλειφθῆναι] + a domino Η | 29 πάντῃ] + α domino Η.
11 ὁ ἐλευσόμενος] in eoelo et in terra H | 13 έ)σται mit Η: futura est ἔστι S | 13/14 περὶ — εὑρισκομένου] qui omnia quae sunt Ventura cognoverat Η | 19 τὰ γενναῖα] so auch S (vgl. TU NF 1, 3, 6 Α 2 10, Α 2) τῇ γενεᾷ Co | 21 μὴ θλιβομένη] lugentium Η | κατηχούμενοι] + in jwima statim fide | 22—24 καὶ Η ganz ungenau w. e. sch.: qiiando mulierculae et infirmior sexiis usqiie ad mortem manebat intrepidus | 24/25 τότε — τεράστια] Tune vere signa de coelo, tunc fiebant portenta de terra H.
3 γὰρ streicht Ru mit Η | 6 πρῶτον mit Ru nach H: prhnum πρὸς τὸ S | ὅτι] ὅτε Co | 10 τὰ Blass | 14 χρηστὸς Co χ#x772; ς#x772; S Christus Η | ἐξέκοψε·ν· S | 17 γὰρ δὲ S &lt; Η | 20 θεὸς Co (+ ἀμφότερον ἔχει) Dcits Η θεοῦ S | 22 καὶ1 Hu et Η (Vall.: stcquc) εἰ S | per Proplietam Η | 23 ἐποίησάν μοι] fccit miJu Η ἐποίησέ μοι Co | 25 κατασκίου] nemorosmn Η (= ἀλσώδους) | 26 ἀναβαινον (??) i. Τ., a. R. ἑστι | [1. ἑστῶτα?] S, asccndentcm Η.
3—17 Hierzu Fragm. 8 in C: Ἐπὶ— ἄλσος | 4/5 ψεκτῶς—ὑπερηφανίαν] et arrogantia ista praesumat H | 17/18 ἔχεις — ἀπηγορευμένον] nominatim quippe interdicitiir ne lucus plantetur in templo, si observaveris quare dictum Sit Η — vielleicht ist ein εἰ νενόηκας διὰ τί εἴρηται als Anfang d. § 5 ausgefallen | 24—27 δέον — ἐγκαταλειφθησόμεθα] &lt; Η | 28 Joannes Baptista H.
1 ἐσκληρυμμένους vgl. S. 50, 20/21 ἐσκληρυμένους S | 2 ἤγειρε] suscitanit H (-bit Vall.) | 3 ἐν τῇ τεκνογονίᾳ] in adoptione ejus Η | 5 εἶδεν Ru vidit Η εἶδον S | 6. 8 κατελείφθη] comprehensa est Η κατελήφθη Hu | 7 ἐὰν ἀναγινώσκωμεν nach Η: legentea ἀναγινώσκομεν S | 16 κληθέντες] et ideo nos vocatos Η | 18 εἰ δὲ nach Η: autem εἰ ἤδη S | 23 πεποίηκα τῇ κατοικίᾳ] fccit hahitatio Η, danach Hu kaum lichtig: πεποίηκαν [1. κεν] ἡ κατοικία | 25 γεγενημένων] + ut ne ipsa propter peccata sua, similia sustineret H, vielleicht richtig | 26 τίνα] ab aliquo conserro qiiis Η | 28 μεῖναι nach Η: perscverare.
4/5 ἐθνικοὶ — θεῷ] et postea ex gentihus congregati credidimus in Christum Η | ἀναγινώσκωμεν Ru legamus Η ἀναγινώσκομεν S | 8 ἀπὸ] de haereditate Η | 10 καὶ αὐτή Hu et ipsa Η ἑαυτῆ S καὶ αὐτῇ Co | 14 πορνεύομεν Ru | 15 καὶ2] + in his omnibus H, vielleicht richtig | 18/19 ἐπεστράφη — οὐκ nach Η: est Gonversa ad me praevaricatrix Juda ex toto corde suo (Vall. + sed in mendacio). Neque vero | 20 ἐπέστρεψεν] est conversa ad me Η | ἔστη] tacuit Η ἐσίγησε Hu, doch vgl. z. B. in Matth. Tom. 10, 19 (Lo 3, 53): καὶ ἔστη | 22 ἐπέστρεψεν — ἐπιστροφή ἐστιν] ut ostenderet eos qui convertuntur, in mendacio, non in vcritate converti Η | 22/23 τὰ παλαιὰ] reteris Testamenti historias et prophetas Η | 25/26 τὰ — λόγους] Evangelia et omne novimi Testamcntum. Legamus apostoli Pauli Epistolas universas Η | 27 μὴ übergeschr. S1 | 28 καὶ mit H: et.
1 διδάσκων] + in commune populum siium Η | 2 παντοκράτορα θεὸν] auch Η (omnipotentem Dcum) vgl. Huet Orig. II, 2, 2, 29 (Lo 22, 208) | 20 ὅτι Co LXX ἣν S | 27 καὶ streicht Blass.
ἐπεὶ ἐὰν Blass εἶτ’ ἐπειδὰν Lietzmann.
3 διεμέριζεν Co διεμέριζες S | 8 οἵδε] vgl. S. 31, 33 μερίδες σου Co | 15 ἀλλὰ] + καὶ Co | 19 καὶ] vielleicht ist τὴν úgen | 21 μνημονεύωμεν Co μνημονεύομεν S | 24 μὴ των τοῦ S | κύριος] vgl. S. 33, G. 14 #x772; S | 29 ὁ] &lt; Gh.
10 ἐτύγχανε καὶ Gh | 21 ὅτι ἄνθρωποι vgl. S. 34, 2 ὅτι θνητοὶ Gh. ὅτι Ru | πρότερον] + θνητοί Ru | 22 γεγεννημένον Lo γεγενημένον S | 24 μεταβεβηκότα S | 27 μὲν] streicht Blass | οἱ Gh.
4 τὰ Blass | φασιν Ru φησὶν S | 5 οὐ Ru νῦν S | 6 αὐτοῖς Blass αὐτὰ S | 7 χρησμοὺς] + ἀληθινοὺς εἶναι χρησμοὺς Lietzmann | 10 ἀληθείας GhCo ἀληθούς S | 11 δὲ Blass μὲν S | 13 ἀλλὰ nach Lietzmann | 23 σωθησομένου Gh σωθησομένων S.
4 κἂν] καὶ Gh Blass | 9 τὴς] 1. πᾶς ? | 12 δουλεύσουσιν (Gli)Co δουλεύουσιν S | 13 περάτων] vielleicht ist nach c. Gels. 8, 72 (Orig. II, 289, 21) ποταμῶν hinzuzufügen 14 ξζ΄ S | 17 Ἰακώβ] &lt; LXX | 26 αὐτῶν1] + καὶ Gh | — S. 36, 10 Hierzu Fragm. 10 in C: Εἰ— Σιών | 28 μοχθηρὸς] ἄτοπος C | 29 ψευδὲς C ψεῦδος S.
10 τῶν Gh | 13 πρόβατα] + τῶν πατέρων Gh | 13—S 38, 6 Hierzu in C: Πρόβατα — Χριστός | 15 τῶν πατέρων] &lt; Gb (vgl. Ζ. 13) | 19 λέγῃ Gh λέγει S 23 ποιμαίνοντα V ποιμένοντα S | 25 γένηται Hu γενέσθαι S | 26 αἰσθήσεων] + καὶ Gb | 27 Ναβουχοδονόσορ V Ναβουχοδονόσωρ S (vgl. Index).
1 ἔστι τι C έ)στιν S | 2 ἢ GbCo ἡ S | γεωργοῦν Gh | 5 μόχθος2] μόσχος C | 7 τίνων αὐτῶν ἢ Co τινῶν αὐτῶν ἡ S τίνων αὐτῶν οἱ V | 8 ὑπὸ Gh ἀπὸ S | 14 ἡμᾶς δὲ μὴ εἴη ποιεῖν Gh (nacb C: ἡμῖν δὲ μὴ γένοιντο) ἡμᾶς δὲ ἀπείη ποιεῖν Co | 18 φησὶν] vgl. S. 38, 6 | 18—S. 38, 12 Hierzu Fragm. 12 in C: Τίνας — ῥηθέν 20 ἀναγινώσκεται S* ἀναγινώσκηται S1 | 21 κεῖται VCo | 22 συνήσει Lo συνίσει S | 26 μ΄ καὶ γ΄ S.
3 ὢν κεκαλυμμένον] ἀνακεκαλυμμένον S | 5 μ΄ καὶ γ΄ S | 13 αὐτὴ V Co αὐτῆ S | 14 ἠ τὸν υἱόν streicht Co | 22 αὑτου Gh | 24 οὐχ οἷον] οὐχὶ Gh | 25 περίθου1 S1 περιθοῦ S* | 32 περιαιρεθῆναι V περιερρηθῆναι S.
5 χείρας V Co χώρας S | 6 περιείλομεν] περιείλωμεν S; der Satz scheint lücken- haft | 8 τῷ Blass Koetschau | 10 αὑτοῦ Diels αὐτοῦ S | 12 ἡμάρτομεν Gh Co ἡμάρτωμεν S | 13|14 προσωποποιείαν S | 20 τριθημερινάς Blass | 23 οὔπω Gh Co οὕπω S οὕτω V | 25 ἀπαλειφθῆναι Gh vgl. Index | 34 ἔτι χρόνου] επιχρόνον S.
4 ἐὰν Co | 5 οὐκ ἐὰν Blass | 9 εὐλογήσουσιν Hu | 21—27 Hierzu Fragm. 13 in C: Καλῶς—αὐτῶν | 26 πρόσωπρον S | 29 αὐτοῦ1 Co | 31 ἴδωμεν] οἶδα μὲν [sic] Hu| 35—S. 41, 19 Hierzu Fragm. 14 in C: Πῶς—ἔθνη.
5 ἔχειν] ἔχη S | 6 μαρτύρων Co | τοῦτο] τὸ οὔ S τὸ ναί Co | 7 τοῦ Co τὸ S | ὀμόσῃ Co ὁμόση S| 11 γίνεται Gh γένηται S | 13 καὶ Co | 14 τὴν Gh ἣν S | 15 θεραπεύων] l. μαρτυρῶν? | 16 ἁμάρτοιμι V Co ἁμάρτιμοι S | 17 ζῇ Gh Co | 18 εὐλογήσουσιν Gh εὐλογήσωσιν S | 19 ἀμφότερα] ἀμφοτέρονς C | 20 εἶπεν 2 V εἶπερ S | 28 ἔχομεν] ἔχωμεν S.
1—30 Hierzu Fragm. 15 in C: Ὁ—αὐτά | 10 ἀναπαύσεως VCo ἀναπαύσεων 11 τὸν 1 VCo τῶν S | 15 σὺ Gh σοῦ S | 18 ἀπάτη καὶ nach Mattk 13, 22 Mark. 4, 19 vgl. Exhort. 49 (s. ob.) | 20 Ἰησοῦς] Χριστός C | 30 δόξει ἀνατέλλειν Gh δόξη ἀναστέλλειν S | δ’ ἀληθὲς] ἀληθῶς S.
1 αὐτὰ VCo ἄττα S w. e. seh. | ἀνατελεῖ Blass ἀναστέλλει S | 5 ἀλλ’ Co | 14 αἰτῇς Hu αἰτεῖς S | 16 ὑμῶν Co | 21— S. 45, 5 Hierzu Fragm. 16 in C: — γενήσεται | 25 ὑμῶν V ἡμῶν S.
3 περιABBREVτμήθητε S | 5 οὐκοῦν Co οὐκ ἀν S | της S* τις Scorr. | ἀκροβυστίας S* ἀκροβυστία Scorr. | 11 περιτέτμηται S | 14 εἰ V Co ἡ S | ἡμέρα] ἡ über εἰ S | 20 καὶ Gh | 30 εἰ] ἡ V.
3 κατοικῶν ἐν Ἱερουσαλὴμ καθαρὸς περιτετμημένος C | 5 ἴδωμεν] δ über ει S | μή πως] μὴ LXX, vgl. μήποτε L XX Luc. | 15 ὑμῶν Co ἡμῶν S | 17 ἀναγγείλατε] &lt; LXX | κεκράξατε] vgl. Ζ. 29 | 26 ἄλλῳ] + δέδοται Blass | 30 — S. 46, 10 Hierzu Fragm. 17 in C: Εἰς — ἁλίσκεται.
1 τεῖχος] + ὡς ? aber auch damit äre nicht alles in Ordnung. Psal. 17, 30 καὶ ἐν τῷ θεῷ μου ὑπερβήσομαι τεῖχος kann kaum gemeint sein, da dieses τεῖχος sonst von Origenes auf die ἁμαρτία gedeutet wird (Sei. in Psal. 17, 30 Sel. in Thren. 3, 43). Oder ἐν — θεός ist Glosse eines Mannes, der Psal. 17,30.31 las: καὶ ἐν τῷ θεῷ μου ὑπερβήσομαι. Τεῖχος ὁ θεός μου κτλ. (Riedel) | ιζ΄ S | 6 τῶν] l. τούτων ? | 8 τειχήρεις VCo στειχήρεις S | 10–23 Hierzu Fragm. 18 in C: —γῆς | 16 θ΄ S | 18 ργ΄ S | 22 πότε] πόθεν? Blass | 25 κρεῖττον S* κρείττων Scorr. | 29 τοῦ] vgl. S. 47, 2.
1 πρὸ βραχέως ροβραχέως S [sic] πρὸ βραχέος? Diels | 2 εἰς Gh | 7 πένθη S* πένθει Scott. | 20–22 Εἰς—ς΄ nach den andern Überschriften.
6 . . . ὀφθαλμοὶ hier scheint ein Vordersatz zu fehlen, etwa ἐπεὶ δέ ἐστι καὶ »ἐκ πίστεως δικαιοσύνη« öm. 10, 6), ὡς ὀφθαλμοὶ κυρίου »εἰς πίστιν«, οὓτως oder ὡς δὲ »ὀφθαλμοὶ κυρίου ἐπὶ δικαίους« (Psal. 33, 16), οὕτως καὶ | 17 τοιαῦται V Co τοιαῦτα S | 21 — 28 Hierzu Fragm. 19 inC: Μακάριον—μαστιγοῖ | 22 ff. Das Citat soll w. e. seh. wörtlich sein; vgl. übrigens in LXX codd. 55 254 | 28 συναίσθησιν (vgl. S. 36, 11) σύνεσιν S | 30 αὐτοῦ Gh αὐτῶ S.
5 ἀναισθητεῖ S | 8 ἴδωμεν V ἴδομεν S | 11 πόνον Ru πόνων S | 13 ᾖ] ἡ S | νεκρότης Co νεκρώτης S | 14 αὐτὸ Gh αὐτόν S | εἶδες V ἴδες S | 16/17 δεινὰ προσφέρεται Gh διαπροσφέρεται S διαπρισθήσεται Co | 19 ἤπερ V εἴπερ S | 21 τῷ Gh τοῦ S | 33 τὸ ἐπ’ αὐτῷ Gh τὸ ἐπ’ αὐτὸ S τότε αὐτήν Co.
3 παρ' αὐτῷ Gh παρ’ αὐτόν S | 7 γίγνηται S vgl. S. 9, 8 | 12 ἀκούοντες VCo ἀκούοῦντες S [sic] | 18/19 τῆς ψυχῆς Gh Ι 31 — S. 51, 6 Hierzu Fragm. 20 in C: Πρὁς—ἀκροατάς Ι 33 καὶ] κατὰ V, doch vgl. Ζ. 36 Ι 34 προθέσεις V1? a. R. Co προσθέσεις S.
2 Wörtliches Citat? διὰ τοῦτο statt διότι haben in LXX codd. Α 22 Basil., Formen von ἀκούειν Chrys., Basil. Ι 5 ἐάνπερ τύχῃ] ἐὰν πορἐύση S [sic] Ι 8 αὐτῶν] αὐτοῦ S 1 12 Ἀμήν] + ὁμιλία ς΄ S | — S. 52, 20 Hierzu Fragm. 21 in C: Φιλάνθρωπος — ἔρημος | 20 κρίνων] κολάζων S | 21 τούτου Hu τοῦτο S | 25 έ)σται] &lt; C.
.
Co 1 10 εἰς Blass | 13 δουλεύσετε] + ἀλλοτρίας [sic] Co; doch müsste man nach Ζ. 24 θεοῖς ἀλλοτρίοις einfügen, wenn überhaupt zu ändern ist | 25 πᾶς θεοποιῶν vgl. Ζ. 35 πᾶς δὲ ὁ ποιῶν S πᾶς δὲ ὁ θεοποιῶν Co Ι 34 προσκυνήσῃ V προσκυνήσει S.
6 προσ|σκυνήσεως S | 7 ἑαυτῶν Gh | 10 ζωῆς] σοφίας LXX | 14 τὰ ἀλλότρια streicht Gh Ι ἀλλοτρίοις vgl. S.53, 35 | 21 1. ποιῶμεν ? | 22 ἴδωμεν VCo S | 24 τοῦ 2 V ποῦ S | 25 ἐπ(??) S | 34/35 αἰῶνας] + τῶν αἰώνων V Ι 35 Ἀμήν.] + ὁμιλία ζ΄ S.
1 — 2 &lt; H | 3 Ὁμιλία ή] in S steht dies vor Z. 1; doch vgl. die andern Überschriften. Homilia V Η und Epist. VIII unter d. opera supposititia d. Hieronymus vgl. TU NF I, 3, 109 Ι 4 τοῦ θεοῦ] &lt; H | 6 ἀπονέμει nach Η: distribuit | 7 οὐρανόν Co coelum Η ἄνݲοݲνݲ S | 15 ἐπεὶ Co w. e. seh. Siquidem Η ἐπὶ S | 18 εἰ δύνασαι ἰδεῖν] et consideres H | 21 ἔρχομαι] veniatn vero H | 22 εἰ2 nach Η: (Si enim non habet deum Patrem,) si (non habet Filium dicentem).
1 τὸ τὸν S* Ι 3 τούτων τῶν] tresH Ι 7 τὸ πνεῦμα τὸ ἅγιον nach Η: Spiritus sanctus est vgl. Hu Ι 9 ἢ Co ἡ S | 14 βουλώμεθα δὴ nach H: hhorare nitamur βουλόμεθα δὲ S | 17 ἡδικήσαμεν] + impie gessimus Η ἡνομήσαμεν?) Ι δεῖται Koetschau vgl. Ζ. 24. 25 δέεται S | 20/21 ζήτει — οἰκουμένην] &lt; Η | 22 οὗν] a. R. Scorr. | 23 ἐὰν — οἰκουμένην] &lt; H | 23/24 πρὸ— πέπτωκε nach Η: ante ereciionenfii cecidit. Si autem cecidit | 24 δὲ2] quippe H | 25/26 εἰ—πτῶσις nach Η: Si aiitem erectus est, uideamus quae ruina praecesserit | 27 κατεραγμένους S.
5 ἥν μὴ] μοι μοι Co | εἰ μὴ nach. Η: qitam nolo ut extra Christum requiras Ι 13 ἀπονεμητικὴν Hu ἀπονεμιτικὴν S | 14 ἁγίους] vgl. Hu sanctos Η ἁγίου S | 15 ἐπιστήμη Co ἐπιστήμης 8 ’ina et demonstratio H | 16 — 20 ἐπεὶ — παραστήσω] ݲ H | 23 δηλοῦται — τῷ] Audi H | 24 ἔκτασιν Co extensionein Η ἔκστασιν S 24/25 οὕτως — οὐρανός] Similiter et nunc dicitur coeli | 25 ργ΄ S | 29 οὐράνιον Co ὀυνὸν S.
2 ἢ Co aict Η ἡ S | 8 ἐπι Scorr. ἐπειS* | 15/16 εἰς — νοουμένου] textnm sermonis agnoscant, quem timc, prout voliiinms, exposuimus H | 17 ἐλέγομεν nach H: diximus | 17–20 Hierzu Fragm. 25 in C: Ἀνάγει—θεοῦ | 18 ἀψύχους ἀψύχως S* w. e. seh. | 20 ἐκπέμπουσιν S | 23 τῶν] + qnue ex denso acre dicuntur constarc H, wohl nur ückung | 26 τρίτῃ Co Ι ὅπου] ὅτε Blass Koetschau quando Η ὁ τὸν S.
3 ὅταν ἀναξία Co cum iiidigna H | 4 τυγχάνῃ .... ἐντελοῦμαι Co τυγχάν [sic] .... ἐντελλοῦμαι S | 8/9 εἰ—μου nach Η: Si non fuisset nuhes, numquam dixisset: Exspedentur ut plunia verha mea | 13 ἔλεγεν δὲ] et sciebat H | 22 ἐστι] + sanctus Η (vgl. Ζ. 5) | 27 τοῦ θεοῦ] eoelorum H | 32 ἀπόστολος ] sim apostolus Η ἀπο- στόλους ὡ S.
1–8 Hierzu Fragm. 26 in C: Δέγουσιν— ἀστραπῆς Ι 3/4 ἐπὶ λίθων C | 13/14 οὕτως — συνάγαγε] Poles et fu ipse ... inrenire H | 18 ἆρα οὖν nach Η: Ergone ὅρα οὖν S | θησαυροῖς] + Dei H | 19 ἢ Co et H ἠ S | 20-31 Hierzu Fragm. 27 in C: Κατὰ — ἑξῆς | 24/25 τὰ -- ἔστίν et istorum spirituum inrenire thcsauros H.
1 ἐπεὶ] nach H: quia Ι 5 συμφύρεται Ru miscentur Η συμφέρεται S | 9 καὶ] &lt;H | 11 πολλῶν] + alias H | 26 δὲ Co sed H | γνῶσις] &lt; Η, Recht | 33 ἑαυτὸ] ἐαυτὸν S.
1 ἑαυτὸ nach H: se Ι 9 ἀποστόλοις, πᾶσαν] cactcris apostolis H, vielleicht richtig | 11 οὐ nach H: non o=yn S | 17/18 τῶν ἀνθρώπων] honunibiis Η, zu streichen? | 22 δύναται potestYL δύνασαι S | σοφίαν] + Dci H | 24 ὁσπερ S* ὁπερ S1 | 32 ἐàν — νοήματα] &lt; H | 33 ὀλίγῳ] ὀλίγου S.
3 αὐτήν nach Η: (cum) ea αὐτόν S | αὐτὴ] αὐτη S quae Η αὕτη Co | 11 αἰ- ῶνας] + saeculorum H | Ἀμήν] + ὁμιλία ή S | 13 λέγων Co LXX dicens Η ἀπὸ τῶν S | 16 Homilia VIH | 20 —23 ἦν — παρέλαβον] H | 27 ἀκούσατε] Audi Η.
2 Ἰεζεκιήλ — ὁνδήποτε] quemlibet pro[hetarum? | ἢ Lietzmann An ille est Η 6 οὓς—ὄνασθαι] haee sit utilitaw credentium, si H | ὄνασθαι] ὀνᾶσθαι S ἐνοῦσθαι Co | 8 ἔχω Hu vgl. Z. 10 habecnn Η ἔγνων S | 12 δικαίων] sanctorum Η | 14 καὶ ἐγίνετο] &lt; H | αὐτοῦ] + quem omnibus manifestavit Η | 16 πῶς] + cnim H | 19 (leuni H | 20 καὶ nach Η: et | αἰῶνας] + saeculorum, Amen H | ἔσονται Co siuit Η ἴσονται S | 24 νῦν] + et unum Spiritum sanctiim, cum Patre, et Filio scmpitcrnum vgl. TU NF I, 3, 27 | 26 οῦν] + dicoi H.
2 κατὰ τὴν γραφὴν nach Η: juxta Scripturas καὶ τὴν γραφὴν S καὶ τὴν ἀπογραφὴν Co | 9 οὑ] &lt; Hu mit H | 13 Ἰησοῦ] mei Jesu Christi H | 16 εἰ τοῦθ' Co οὐθ' S | 17 ἄνδρας mit Η: viros ἄνδρα S (der hexaplarische LXX cod. 88 hat ἄνδρα, doch überwiegt in S selbst die Lesart ἄνοδρας vgl. S. 64, 27. 28 65, 3 u. 66, 2) | 18. ἢ Co ἡ S | 19 πρὸς ἄνδρας Ἰούδα] Co (vgl. zu Ζ. 17) πρὸς ἄνδρα ἰούδαν S &lt; Η | λέγεται] Fit quoque H | 21 τοῦ θεοῦ] magni Regis H | 22 ἐστιν] &lt; Η w. e.
Blass.
7 εἰς ἅπαξ Co LXX in semel H | ἐτέχθη — ἅπαξ 2] &lt; H | ἐπιδεδήμηκεν] ascendit ad coelos Η (= ἐπαναβέβηκεν?) | 13 ἔρημος μὲν ἠ ἐκκλησία vgl. H (Deserta Ecclesia α Lege) u. d. Parallelen | 14 νόμον] + habebat et Deiim H, w. e. scb. frei | 20 ἔσομαι] + inquit (od.: quid) H | πότε οὖν ἄρα] Putasne aliquando H | 21 θέλεις] + plenius Η | 23 Ἀβραάμ u. Ἰσαάκ] + καὶ C + et Η.
5 καὶ μένων μετ' αὐτοῦ] et fit particeps ejus H | εἰ] et siH Ι Q ἵνα] ut et Η | 7 αὐτοῦ] + in nobis H | –15 Hierzu Fragm. 30 in C: Τῶν — γῆν | 12 τὴν Blass | 12/13 ἣν — ἐκείνη] quam pollicitus est deus, terra fluens lac et mel; sed illa est terra H | 13 ἀλλ' ἔστιν εκείνη nach Η (s. ob.) ἀλλὰ περὶ ἐκείνης S ἀλλ’ ἐκείνη Co | 19 ἐμμενεῖ Diels ἐμμένει S auxiierit H | 22–26 Hierzu Fragm. 31 in Ἀναγινώσκομεν — Ἱερουσαλήμ | 24 καὶ οὐκ ἐποίησαν] &lt; H | 26—S. 69, 1 ἦ — προφήτης] Si peccaverimus nos qui uiri Juda proptcr Christum uocamur et invenfi fuerint in nostro numero peccatores de nobis dicitur H | 26 ἦ Lietzmann τί Blass εἰ S(H) | 28 λεχθέντα Co vgl. S. 65, 19 ἐλεγχθέντα S | 29 τὸν ὁρθὸν Co τῶν ὁρθῶν S.
2 — 8 Hierzu Fragm. 32 in C: Κὰ)ν — προσέθηκεν | 4 ἐφαρμόσαι — τὸ2] id quod de peccatore dieitur, eis valeat convenire Η | αὐτοῖς τὸ nach Η Diels Lietzmann | 7 εἰ nach H: si (vgl. auch Ru) ἠ S | 8 λῦε] Sed: Solve Η | 9 συναλλαγμάτων Hu συναλαγμάτων S | 13 οὐ λέγει nach Η: non ait λέγε S | 17 τὰς ἀδικίας Ru ταῖς ἀδικίαις S | 18 αὐτῶν nach Η: suorum | 18 — S. 70, 14 Hierzu Fragm. 33 in C: Καὶ—κατορθώσωμεν | 20 ὡς nach Η: ut οὓς S | 22 οὖν] + post haec Η | 25 μδ΄ S | 27/28 πατὴρ — σου] &lt; Η | 30 τοῦ οἴκου2] streicht Co inquit Η.
1 ἐὰν] + igitur Η | σου τοῦ οἴκου] domum patris tui Η | 2 σὺ πεποίηκας] incidisti in Η οὐ πεποίηκας S | 4 ἔλεγον] + dudum Η | 5 διάβολος Co (vgl. H) διάβος S [sic] | 6 καθολικῆς] &lt; Η | 8 εἰ πᾶς Co Si omnis Η εἶπας S | 25 ück findet s. in ’ Apologie c. 4 (in lat. Übers. Migne PG 17, 564), vgl. TU NF I, 3, 112 f. | 23/24 ἀλλὰ — με] sed generat me Pamph. &lt; Η | 24 καὶ ἀεὶ] semper Η | 25 ἐὰν — πνεῦμα] si tarnen adoptionis habes Spiritusn H | 2526 γεννᾶ σε — ὁ θεός] generaris α Deo Η | 28 Ἀμήν] + ὁμιλία θ΄ S.
1 τοῦ] + Ite (= βαδίσατε) Η | 4 Homilia VIII Η | 11 ὁ πατὴρ δὲ ὁ ἐν τοῖς οὐρανοῖς nach Η: Pater autem quiest in coelis | 13 ἢ] zu streichen? Blass | φέρ᾿ εἰπεῖν] ut ad ininora veniamus Η vgl. TU NF I, 3, 27 Α 2 | 1 7 γνῶ] ipotuero nasse quod nescio Η | ἐπιτηδεύματα] cogitationes Η | 18 ποίας Hu cuius Η ποία S | 19 εἶτα nach H: Deinde εἶ δὲ S εἰ δὲ Co | 21 καὶ] &lt; Η | 25 κείραντος] + se Η | ἐκεῖ) et ibi Η | αὑτοῦ nach Η: se ipse αὐτοῦ S.
1 ἐπὶ σφαγὴν] &lt; Η | 2 ἔγνω Co cognoverit Η ἔγνων S | 3 ἁμαρτίαν] sive injustitiam Η | 9 καὶ] &lt; Η | 10 αὐτὸν] Dominum Η (1. τὸν #x772;? | πῶς δὲ τοῦτο ἐφαρμόσεις τῷ] quomodo vero aptabimus ei, quod dicitur Η | 12 λέγοντες] + hoc quod infertur Η | 13 καὶ] &lt; Η | 15 ἠθέλησαν] + quidmn Η | streicht Blass &lt; Η | 16 εἶπον] + venite (= δεῦτε) Η | 20 καὶ] &lt; Η admirabile quiddam Η | 22 λαμβάνω] accipe Η | νόμου] + Sicut Η | 24 λόγον] doctrinam ejus Η.
1/2 διὰ τοῦτο] tunc Η | 3/4 καὶ — γίνεται] In cujus flgura et aqua in Veteri Testamento ad taetum ligni dulcis effecta esi Η | 5 Ἰησοῦ] + Christi Η | 8 καὶ] &lt; Η | 14/15 septuplum et multo amplius Η | 15 ὡς εἰ καθ’ ὑπόθεσιν] Fingamus enim paulisper Η | 16 μηδὲ τεθνήκει] μὴ δὲ τεθνήκει S neque post mortem ad inferos deseendisse Η | 17 ἐγένοντο] ἐγίνοντο S | 18 λέγειν] vgl. Η: (velint) intellegi λέγων S | 21 τοσούτους] vgl. H: tantas (attulit fruges) | ἐκαρποφόρησεABBREV S | 24 αὐτῶν Co eis Η αὐτοῦ S | 25 παρὰ τοῦ θεοῦ] apud Patrem Η | 27 καὶ εἴρηται αὐτῇ] et id quod dictum ad eam fiierat . . . . completum est Η | ὑμῶν] + deserta Η | 28 ἐν αὐτοῖς] de eis Η.
nach Η: adventum Domini πόρθησιν S; vgl. S. 52, 19.
1 οὐδὲ διδασκαλία] Neque magistri, neque doctores in Jiidaea aliqui remanserunt H, vielleicht richtig | παρ’ αὐτοῖς] qui sibi (sapientiam vindicent) = παρ αὑτοῖς Η | 2 πεπλήρωτο] ἐπεπλήρωτο Lo | 4 ἰσχύουσαν] + virtutem panis, et virtutem aquae H, vielleicht richtig | 8 μετέβησαν] + ab eis Η | 10 ἐκείνους] + (quicomque..) cumque..0 crediderunt Η | 11 ἐπ’ αὐτοὺς] &lt; Η | 14 τί Co LXX quid est Η | 15 ἕτι ζητοῦμεν] Quaeramus Η | 17 οὐ κολάζει τοὺς ἀσεβεῖς] nihil eos ab eo pro merito sustinere Η | εὐθήνησαν] + enim Η | 20 κaὶ ἐποίησαν Ru vgl. Ζ. 24, Fragm. ἐξ ἀνεπ., LXX, et fecerunt Η | 24 τὸ Ἰησοῦ ὄνομα] Jesum Η.
1 ὡς χρή] so auch Fragm. ἐξ ἀνεπ. ut Christum Η | 2 με, εἶδες με] et Η | 5—7 Hierzu Fragm. 36 in C: Δι’ — παιδεύει | 8 ὁ χόρτος] fenum omne Η vgl. Luc. | 9 αὐτῇ] terra Η | 9 — 27 Hierzu Fragm. 37 in C: Εἰ— ἀρετῆς | 15 ὁμοίως ἐρῶ] ex quibus H, doch vgl. S. 77, 3 | 22 τὴν ἐν τοῖς] ad ipsa quoque H, vielleicht richtig | οὐρανίοις ἄστροις nach Η: astra coelestia coelestia ἄστροις S | 22—24 ἄγγελός — ἄστρων] Alius angelus praepositus est stellis H | 25 ἐὰν δικαιοπραγῶμεν nach Η: quamlo juste agimiis vgl. S. 72, 8 | 26 πενθεῖ, φησίν] Lugebit H | ἀπὸ] + Omnibus H | 27 — S. 77, 3 ὥσπερ — ὀνόματι] Quomodo enim hoc quod manufactum est maledicitur et ipsum et qui fccit illud .... sed id dicitur manu factum quod assidet insensibili simulacro, eodem vocatum nouiine, quo vocatur id quod manufactum est H.
3 δὴ ἐρῶ καὶ γῆν λέγεσθαι Co sic et nunc terra appellatur Η δ’ ἐρῶ καὶ γῆν λέγεσθαι καὶ γῆν in Ras.) S | 4 ἄγγελον] + Nec hoc tantuni accipias in terra Η | 5 ἵδοσαν—θεός &lt; Η | 6 πλήθους] Multitudo Η | 10 ἐν Co ἐμ S | 11 Thronos, et excelsas quasque Virtutes Η (vgl. Kol. 1, 15?) | εἰ βούλει καὶ] Si autem vis aliquid Η | 12 πατρί] + et Pater in me H, vielleicht richtig Ι τὸν θεόν] Patrem Deum Η | 14 ἀφῆκα Co (vgl. H) ἀφῆκας S | 16 δυνάμεων in Ras. S | 24 ἣν κεκληρονόμηκεν] quam sibi elegerat in possessionem, quae pars ejus fuerat Η | 25 Ἰουδαῖοι ἐξαγριωθέντες κατ' αὐτοῦ] id est Judaei Η | 26 οὐ] Νec Η.
2 τὸν] Dominum Η | 3 εἰς αὐτόν] nomini ejus Η | 5 μου] Hierauf folgt in S 251r 251v erst Hom. 11, 1 von τὸ ἀποκτεῖναι τὸν χριστὸν S. 79, 9 bis 11, 3 ὠφελήσει καὶ ὑμᾶς καὶ ἡμᾶς ἐὰν S. 80, 16; darauf 251v 252r 252v Hom. 10, 8 von προφητεύει περὶ τῆς κληρονομίας S. 78, 6 bis Hom. 11, 1 δεδιωχέναι τοὺς δικαίους S 79, 9. Die richtige Ordnung ist von Huet nach Η wiederhergestellt Avorden | 6 ἐμοί Lo vgl. Z. 9, mihi H, LXX | προφητεύει Hu προφητεύη S | 10 ἢ nach LXX u. H: auf ὡς S | ἐπ’ αὐτήν] &lt; Η | βαδίζετε] &lt; Η | 12 τοῖς θηρίοις] ad dilaceramlum Η | καὶ] &lt; Η | 16 ὁ Ἰησοῦς] Dens Η | 20 ἔχομεν] ἔχωμεν Hu confidamus Η | 23 μεταβιβάζουσιν | + de terrenis locis ad eoelestia Η | 24 ἐπὶ τὸν μέλλοντα] in perpetuam aeternitatem Η | 25 τὸ — αἰῶνας] gloria et imyerium in saccula saeculorum Η | Ἀμήν] + ὁμιλία ι΄ S.
2 καὶ εἰς τὸ περίζωμα] usque ad eum locum in quo ait: Ucee computruerat, quod nullo esset usui Η (et in istud: Cinctorium Vall.) | 3 Homilia VII Η | 8 τῷ Ru ad (occisionem) Η τὸ S | 9 τὸ — S.80, 16 ἐὰν] Vgl. zu S. 78, 5 | 11 ὑμῶν] + deserta Η | 12—15 Hierzu Fragm. 38 in C: Εἴποις — ἑαυτῆς | 14 ἐλ- θόντος — γὰρ] et tunc videbis, post adventum Jesu Christi impleta esse quae dicta sunt Η | τῶν μελῶν] membris nostris Η ἡμῶν τῶν μελῶν C, vielleicht besser | 16 τὰ ἔργα τῆς σαρκὸς] &lt; Η | 18 — S. 80, 5 Hierzu Fragm. 39 in C: ὁ — αἰώνιον | 19. 20 ἐπὶ τῆς γῆς] super terram Η.
1 καὶ 1] id esi H | 2 ὅτε] quin H ὅτι Hu ] Ἰησοῦ] Jesu Christi H Χριστοῦ C Ι 6 — 11 Hierzu Fragm. 40 in C: Σπείρουσι — αἱρετικῶν Ι 6 σπείρετε Hu seminatis Η σπείρατε S | 7 ἐν] &lt; C Ι λογίοις wie S. 71, 5. 6 λόγοις C Olymp, (vgl. auchH) ἁγίοις S Ι 7/8 κἂν — πισεύοντες] Qui enim neque Juxta uoluntatem Scripturarum; neque jusxta fidei veritatem proferunt unt eloquia Dei H | 9/10 ταῦτα νοῆσαι vgl. Η: Hoc faeiunt haeretici κατανοῆσαι S | 13 οὐκ Hu non Η τοῦτ' S | 14 εὐγνωμόνως] consentiens Η 16 — 18 ἵ — τοῦτον] mit d. Vorhergehenden verbunden in d. Ausgg., nicht so bei Η | 16— S. 81, 11 Hierzu Fragm. 41 in C: Λέγοις — εὑρεθῇ | 17 τινὲς Hu aliquid R τινὸς S 18 δὲ] &lt; Η | 19 ἀποδειχθήσονται] + sed si ordincm clericatus et mercamur parifer, et habeamus H, vielleicht einzusetzen | 21 ὠφεληθῆναι] (Hu) (Hu) ex ordine H ὀφεληθῆναι S.
4 Vgl. Weish. Sal. 6, 6. — 8 Ι Kor. 4, 1. 2. — 12 Vgl. Sus. 35a (LXX) 42 Θ΄). — 13 Luk. 12, 42 Par. — 15 Luk. 12, 45. 46 Par. 1/2 ὠφελήσουσιν u. ὡφελοῦν Hu ὁφελήσουσιν u. ὀφελοῦν S | 2 καθέζεσθαι Lo καθέσABBREVζεσθαι S καθέσεσθαι Co | πρεβüτερείω S | λόγος] + Verum, carissimi, nolite putare hoc iantimi de nobis esse dictum H | 7 ἀρχὴν] arcem Η TU NF I, 3 22 Α 6 Ι ἔτι πλεῖον] ἐπὶ πλεῖον S pro omni Ecclesia (reddet rationem) H | 8 ἀκούετε] Paulus H | 10 ζητεῖτε] quaeritur H | 13 ἄρα S* ἆρα Scorr. | 15 δούλοις] consercis Η | 17 συνδούλους] servos H | 21 ὠφελήσουσιν Hu ὁφελήσονσιν S | 22 — S. 82, 12 Hierzu Fr agm. 42 in C: Καύχησιν — Χριστοῦ | 24 τινὰ] multa 25 ὑκ — ἀξίοις] &lt;H | 26 λέγοιτ' ἂν Hu dicitur Η λέγει τ' ἂν S.
1 ὑμῶν] + Verum hoc partim est H | ἄκουε — Ἱερεμίου] Audi quid loqitatur in Jeremia seitno divimis H; danach hinter λόγου wohl einzuschieben διὰ | 2 μηδὲ Co ne . . quidem Η μήτε S | 9 ἱ̔να μὴ λεχθῇ] vgl. Η: et Που audire ἵνα μὴ ἐλεχθῆ S | 13 τοῦετο S* τοῦτο Scorr. w. e. seh. | 16 μανθάνομεν] discamus μανθάνωμεν Hu | καυχήσεων Ru (jloriarum Η καυχήσεως S | 19 οἷς] + quippe Η | 22 οὐ Hu non Η | 23/24 καὶ— κυρίου] &lt; H | 25 καὶ ἀνάστηθι] &lt; Η | 27 ἐκεῖ— περίζωμα] propheta, et accepit cintorium de loco ubi infoderat illud, et ecce coinputruerat, quod mdli usui esset H (vgl. Jerem. 13,7) Ι καὶ] + ne quis juxta rohintatem animi sui de hoc loco sibi pracsumeret intellectum H.
1 καθάπερ] † γὰρ LXX QV Luc. + enim H | 3 φησὶν ὁ κύριος] &lt; Η | 4 οὐκ] ἐιυκ S | 5 παραλαμβάνεται] accipiatur Η περιλαμβάνεται S | 6 ὁσφὴν Co ὡς φῦν S | 7 φησὶν ὁ θεὸς] | H | 8 ὁ λαὸς] homo justus H | 9/10 ὁ δυνάμενος] | Η doch vgl. zu Ζ. 13 | 10 τῷ λόγῳ] | Η | 11 τίνα μὲν τρόπον] quamobrem Η | 13 ἐρευνησάτω Ru tunc poteris etiam praesentis Scripturae (inuenire rationem) Η ἐρευνήσατο S | 14 τὰ — ἐστίν] Renes generatione, et lumhi igne cejisentur H | 17 καὶ mit Blass nach Ζ. 14 u. H: ei | 21 τοῦτο] + nunc H | 22 καὶ2 — αὐτὸς] | H | αὐτὸς] ἄνος Koetschau οὕτως Lietzmann | 22/23 ἐν —ἢλεκτρον] Εχ quo unusquisque nostrum juxta exordium natiuitatis suae ad ignem refertur H | 24 — 26 δυνατὸν — ἀνωτέρω] &lt; H | 26 ἀνωτέρωι S.
4 ὁ λαὸς] &lt; H | 6 ὡς ἀποτίθεται Koetschau ἀποτίθεται ὡς S | 9 Ἀσσύριοι] + habitant | 10 ὄντων] Cur etc. H | 12/13 πραγματεύσασθαι — λινοῦν] nisi ut saeramentuni juxta uim nominis doceat intellcctiim H | 14 ὅτι] linum H | 14/15 φυτὸν — εἶτα] nam cum semen ejus in humum fuerit abjectum, primum, in gramme pulhdat, deinde ut infinita pr-acteream H | 16 σμηχόμενον] teritur, tumUtur Η γινόμενον] excutitur H | 19 γῆς nach Η: terra τῆς S | 22 μελανότερον S 24 κατà — ἀρχήν] quando regeneramur, quando crdimus H | 27 γενώμεθα] + ut nitorem qui nobis iusitus ex natura non fuerat, diligentia consequamur H.
