@config
@_book=De Epistola Pinyti ad Dionysium
@author=Pinytus
@availableStructure=fragment
@compiler=Ernst Boogert
@edition=Reliquiae sacrae, Martin Joseph Routh, Pinytus of Knossos, Oxford University Press, Oxford, 1846, 1, Hathi Trust.
@editor=Martin Joseph Routh
@fmt:text-orig-beta-plain={beta_plain} 
@fmt:text-orig-full={orig} 
@fmt:text-orig-lemma={lemma} 
@fmt:text-orig-main={main} 
@fmt:text-orig-norm={norm} 
@fmt:text-orig-plain={plain} 
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=Available under a Creative Commons Attribution-ShareAlike 4.0 International License
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@sectionFeatures=_book,fragment
@sectionTypes=_book,fragment
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@structureFeatures=_book,fragment
@structureTypes=_book,fragment
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:ogl0001.ogl001.1st1K-grc1
@valueType=int
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:35:41Z

